#!/usr/bin/env bash

# This script uses milk-argparse
# See template milk-scriptexample in module milk_module_example for template and instructions


# script 1-line description
MSdescr="Run DM astrogrid"
# Extended description
MSextdescr="DM grid pattern modulation for astrometry and photometric calibration"


source milk-script-std-config

source cacao-check-cacaovars


RequiredCommands+=( cacao-astrogrid-mkgrid )


MSarg+=( "action:string:action (start/stop/check)" )


MSopt+=( "a:amplitude:set_amplitude:val[float]:amplitude [um] (default=0.05)" )
amplitude=0.05
function set_amplitude() {
	amplitude=$1
}

MSopt+=( "n:nbframe:set_nbframe:nbfr[int]:switch pattern every n AO frames (default=2)" )
nbframe=2
function set_nbframe() {
	nbframe=$1
}

MSopt+=( "b:binfact:set_binfact:binfact[int]:bin factor (default=2)" )
binfact=2
function set_binfact() {
	binfact=$1
}

MSopt+=( "p:pattern:set_pattern:pattern[int]:pattern (default=0)" )
pattern=0
function set_pattern() {
	pattern=$1
}



source milk-argparse




ACTION="${inputMSargARRAY[0]}"


echo "CACAO_DMINDEX = ${CACAO_DMINDEX}"
echo "CACAO_LOOPNAME = ${CACAO_LOOPNAME}"
echo "fpsCTRLfifo = ${fpsCTRLfifo}"





echo "$amplitude $nbframe $binfact"

ACTIONOK=0

if [ ${ACTION} = "start" ]; then

echo "start"
# create XY astrogrid pattern
cacao-astrogrid-mkgrid -b${binfact} ${pattern}

sendFPScmd "setval DMch2disp-${CACAO_DMINDEX}.astrogrid.nbframe ${nbframe}"
sendFPScmd "setval DMch2disp-${CACAO_DMINDEX}.astrogrid.delay 0"
sendFPScmd "setval DMch2disp-${CACAO_DMINDEX}.astrogrid.mult ${amplitude}"
sendFPScmd "setval DMch2disp-${CACAO_DMINDEX}.astrogrid.mode ON"

ACTIONOK=1

fi



if [ ${ACTION} = "stop" ]; then

echo "stop"

sendFPScmd "setval DMch2disp-${CACAO_DMINDEX}.astrogrid.mode OFF"

ACTIONOK=1

fi


if [ ${ACTION} = "check" ]; then
	echo "check"
	ACTIONOK=1
fi



if [ ${ACTIONOK} == 0 ]; then
echo "[$(tput setaf 1)$(tput bold) FAILED $(tput sgr0)] ACTION $ACTION undefined"
fi

