#!/usr/bin/env bash

FPSKWname="CACAO_FPSPROC_DMCH2DISP"

FPSKWval="NULL"
if [ ! -z "${CACAO_FPSPROC_DMCH2DISP+x}" ]; then
	FPSKWval="$CACAO_FPSPROC_DMCH2DISP"
fi


# FPS name
fpsname="DMch2disp"
fpsarg0="${CACAO_DMINDEX}"

# FPS full name
fpsfname="${fpsname}-${fpsarg0}"

# function call
fpsfcall="cacaodm.DMcomb"

# short description
fpsdescr="DM channels combination"




function fpsentry_addmodules() {
	echo "no module to be added"
}


function fpsentry_addcmds() {
	addfpscmd "setval ${fpsfname}.procinfo.loopcntMax -1"
	addfpscmd "setval ${fpsfname}.procinfo.triggermode 4" # delay
	addfpscmd "setval ${fpsfname}.procinfo.triggerdelay 0.00001" # 10us
	addfpscmd "setval ${fpsfname}.procinfo.triggertimeout 1" # 1s
	addfpscmd "setval ${fpsfname}.DMindex ${CACAO_DMINDEX}"
	addfpscmd "setval ${fpsfname}.DMxsize ${CACAO_DMxsize}"
	addfpscmd "setval ${fpsfname}.DMysize ${CACAO_DMysize}"
	addfpscmd "setval ${fpsfname}.DMcombout dm${CACAO_DMINDEX}disp"
	addfpscmd "setval ${fpsfname}.astrogrid aol${CACAO_LOOPNUMBER}_DMastrogrid"
	addfpscmd "setval ${fpsfname}.zpoffset.DMcomboutzpo aol${CACAO_LOOPNUMBER}_dmzpo"
}



source milk-fpslist-addentry


