#!/usr/bin/env bash

if [ -z ${FPSLISTADDSCRIPT+x} ]; then
	printf "\e[1;34m[sourced by cacao-fpslistadd]\e[0m FPS add: DM control in sim mode"
else

	if [ ! -z "${CACAO_FPSPROC_DMCH2DISPSIM+x}" ]; then
		echo "CACAO_FPSPROC_DMCH2DISPSIM set to ${CACAO_FPSPROC_DMCH2DISPSIM}"


		if [ "${CACAO_FPSPROC_DMCH2DISPSIM}" = "ON" ]; then

			echolog "ON  CACAO_FPSPROC_DMCH2DISPSIM"
			# ==============================================================================
			# ==========  DM combination ===================================================
			# ==============================================================================

			# FPS name
			fpsname="DMch2disp"
			fpsarg0="${CACAO_DMSIMINDEX}"

			# FPS full name
			fpsfname="${fpsname}-${fpsarg0}"

			fpslistline="${fpsname} cacaodm.DMcomb ${CACAO_DMSIMINDEX}"
			if grep -q "${fpslistline}" fpslist.txt
			then
				echolog "Process ${fpsname} already registered - skipping"
			else
				echolog "Adding process ${fpsname}"
				echo "${fpslistline}"  >> fpslist.txt

				addfpscmdheader
				# infinite loop
				addfpscmd "setval ${fpsfname}.procinfo.loopcntMax -1"
				addfpscmd "setval ${fpsfname}.procinfo.triggermode 4" # delay
				addfpscmd "setval ${fpsfname}.procinfo.triggerdelay 0.00001" # 10us
				addfpscmd "setval ${fpsfname}.procinfo.triggertimeout 1" # 1s
				addfpscmd "setval ${fpsfname}.DMindex ${CACAO_DMSIMINDEX}"
				addfpscmd "setval ${fpsfname}.DMxsize ${CACAO_DMxsize}"
				addfpscmd "setval ${fpsfname}.DMysize ${CACAO_DMysize}"
				addfpscmd "setval ${fpsfname}.DMcombout dm${CACAO_DMSIMINDEX}disp"
				addfpscmd "setval ${fpsfname}.astrogrid aol${CACAO_LOOPNUMBER}_DMastrogrid"
				addfpscmd "setval ${fpsfname}.zpoffset.DMcomboutzpo aol${CACAO_LOOPNUMBER}_dmzpo"
			fi


		fi # end of if [ "${CACAO_FPSPROC_DMCH2DISPSIM}" = "ON" ]

	else
		echo "CACAO_FPSPROC_DMCH2DISPSIM unset"
	fi

fi # end of if [ -z ${FPSLISTADDSCRIPT+x} ]
