#!/usr/bin/env bash

MSdescr="Set astrogrid pattern"

MSextdescr="Set astrogrid pattern

Patterns :
	0 : XYgrid     -> 4 diag spots 45 deg
	1 : Xgrid      -> 2 X spots
	2 : Ygrid      -> 2 Y spots
	3 : Xdiag      -> 2 diag spots
	4 : Ydiag      -> 2 diag spots
	5 : XYgrid0    -> 4 XY spots 0 90 deg

Binnning factor 1 gives maximum astrogrid separation

Astrogrid pattern will be saved as AOcalibs/astrogrid.fits
and copied to shared memory aolX_DMastrogrid
"

source milk-script-std-config


mkdir -p AOcalibs

RequiredCommands=(milk)
RequiredFiles=(LOOPNUMBER)
RequiredDirs=(AOcalibs)

MSarg+=( "pattern:int:grid pattern index" )

MSopt+=( "b1:binfact2:setbin2::use bin factor 1" )
MSopt+=( "b2:binfact2:setbin2::use bin factor 2" )
MSopt+=( "b3:binfact2:setbin3::use bin factor 3" )
MSopt+=( "b4:binfact2:setbin4::use bin factor 4" )
MSopt+=( "b5:binfact2:setbin5::use bin factor 5" )


binfact="1"
function setbin1() {
	echo "set binning factor 1"
	binfact="1"
}
function setbin2() {
	echo "set binning factor 2"
	binfact="2"
}
function setbin3() {
	echo "set binning factor 3"
	binfact="3"
}
function setbin4() {
	echo "set binning factor 4"
	binfact="4"
}
function setbin5() {
	echo "set binning factor 5"
	binfact="5"
}


source milk-argparse

set +u
if [ "${EXITSTATUS}" = "1" ]; then
	exit 1
fi
set -u





pattern="${inputMSargARRAY[0]}"

echo "Pattern ${pattern}, bin factor ${binfact}"

if [ -f LOOPNUMBER ]; then
    AOLOOPNUMBER=$( head -1 LOOPNUMBER )
else
	echo "Error: no LOOPNUMBER file. Are we running this from the correct directory ?"
    exit 1
fi



milk << EOF
mload cacaoAOloopControlDM
cacaodm.mk3Ddmgrid im 50 50 ${pattern} ${binfact}
saveFITS im "AOcalibs/astrogrid.fits"
listim
readshmim DMastrogrid
cpsh im aol${AOLOOPNUMBER}_DMastrogrid
exitCLI
EOF
