#!/usr/bin/env bash

if [ -z ${FPSLISTADDSCRIPT+x} ]; then
	printf "\e[1;34m[sourced by cacao-fpslistadd]\e[0m FPS add: DM control"
else

	if [ ! -z "${CACAO_FPSPROC_DMCH2DISP+x}" ]; then
		echo "CACAO_FPSPROC_DMCH2DISP set to ${CACAO_FPSPROC_DMCH2DISP}"

		if [ "${CACAO_FPSPROC_DMCH2DISP}" = "ON" ]; then
			echolog "ON  CACAO_FPSPROC_DMCH2DISP"
			# ==============================================================================
			# ==========  DM combination ===================================================
			# ==============================================================================

			# FPS name
			fpsname="DMch2disp"
			fpsarg0="${CACAO_DMINDEX}"

			# FPS full name
			fpsfname="${fpsname}-${fpsarg0}"

			fpslistline="${fpsname} cacaodm.DMcomb ${CACAO_DMINDEX}"
			if grep -q "${fpslistline}" fpslist.txt
			then
				echolog "Process ${fpsname} already registered - skipping"
			else
				echolog "Adding process ${fpsname}"
				echo "${fpslistline}"  >> fpslist.txt

				addfpscmdheader
				# infinite loop
				addfpscmd "setval ${fpsfname}.procinfo.loopcntMax -1"
				addfpscmd "setval ${fpsfname}.procinfo.triggermode 4" # delay
				addfpscmd "setval ${fpsfname}.procinfo.triggerdelay 0.00001" # 10us
				addfpscmd "setval ${fpsfname}.procinfo.triggertimeout 1" # 1s
				addfpscmd "setval ${fpsfname}.DMindex ${CACAO_DMINDEX}"
				addfpscmd "setval ${fpsfname}.DMxsize ${CACAO_DMxsize}"
				addfpscmd "setval ${fpsfname}.DMysize ${CACAO_DMysize}"
				addfpscmd "setval ${fpsfname}.DMcombout dm${CACAO_DMINDEX}disp"
				addfpscmd "setval ${fpsfname}.astrogrid aol${CACAO_LOOPNUMBER}_DMastrogrid"
				addfpscmd "setval ${fpsfname}.zpoffset.DMcomboutzpo aol${CACAO_LOOPNUMBER}_dmzpo"
			fi
			
		else
			echolog "OFF  CACAO_FPSPROC_DMCH2DISP"
		fi # end of if [ "${CACAO_FPSPROC_DMCH2DISP}" = "ON" ]

	else
		echo "CACAO_FPSPROC_DMCH2DISP unset"
	fi


fi # end of if [ -z ${FPSLISTADDSCRIPT+x} ]
