#!/usr/bin/env bash

FPSKWname="CACAO_FPSPROC_DMSIMDELAY"

FPSKWval="NULL"
if [ ! -z "${CACAO_FPSPROC_DMSIMDELAY+x}" ]; then
	FPSKWval="$CACAO_FPSPROC_DMSIMDELAY"
fi


# FPS name
fpsname="DMstreamDelay"
fpsarg0="${CACAO_DMSIMINDEX}"

# FPS full name
fpsfname="${fpsname}-${fpsarg0}"

# function call
fpsfcall="streamdelay"

# short description
fpsdescr="streamdelay for simulation mode"




function fpsentry_addmodules() {
	echo "no module to be added"
}


function fpsentry_addcmds() {
	# Run simulator at finite frame rate
	addfpscmd "setval ${fpsfname}.procinfo.loopcntMax -1"
	# tigger mode is delay
	addfpscmd "setval ${fpsfname}.procinfo.triggermode 4"
	# set delay to 100us = 10 kHz
	addfpscmd "setval ${fpsfname}.procinfo.triggerdelay 0.0001"

	addfpscmd "setval ${fpsfname}.in_name aol${CACAO_LOOPNUMBER}_dmdisp"
	addfpscmd "setval ${fpsfname}.out_name aol${CACAO_LOOPNUMBER}_dmdispD"
	addfpscmd "setval ${fpsfname}.delaysec 0.001"
}



source milk-fpslist-addentry


