#!/bin/bash

echo "accessing aolconf_readconf"


if [ ! -v aolconfFLAG ]; then
echo "ERROR: This script should be called from aolconf main script"
exit
fi




# ============== LOOPNUMBER (loop number)
LOOPNUMBER_file="LOOPNUMBER"
if [ ! -f $LOOPNUMBER_file ]
then
	aoconflog "creating loop number $LOOPNUMBER_default"
	echo "$LOOPNUMBER_default" > $LOOPNUMBER_file
	LOOPNUMBER=$LOOPNUMBER_default
else
	LOOPNUMBER=$( head -1 $LOOPNUMBER_file)
	aoconflog "LOOPNUMBER = $LOOPNUMBER"
fi


# ============= loop name
LOOPNAME_file="LOOPNAME"
if [ ! -f $LOOPNAME_file ]
then
	aoconflog "creating loop name loop$LOOPNUMBER"
	echo "loop$LOOPNUMBER" > $LOOPNAME_file
else
	LOOPNAME=$( head -1 $LOOPNAME_file)
	aoconflog "LOOPNAME = $LOOPNAME"
fi









function SelectConfFile {
name="$1"
ffname="./conf/shmim_${name}.name.txt"
fname=$( head -1 $ffname )
echo "fname = $fname"
fname=$(dialog --title "Select  Matrix" --stdout --title "Select ${name}" --fselect ${fname} $nbwlines $nbwcols)
echo "$fname" > $ffname
aoconflog "select configuration file ${name} : ${fname}"
Fits2shm -c -p aol${LOOPNUMBER}_ $name
}











