#! /bin/bash


NBARGS=0
pname=`echo "$0" | sed "s/\.\///g"`




function printHELP {
echo "------------------------------------------------------------------------"
echo "$(tput bold) $pname : Align Pyramid TT $(tput sgr0)"
echo "------------------------------------------------------------------------"
echo "  Align Pyramid camera"
echo "   "
echo " $(tput bold)USAGE:$(tput sgr0)"
echo "     $0 [-h]"
echo ""
echo " $(tput bold)OPTIONS:$(tput sgr0)"
echo "     $(tput bold)-h$(tput sgr0)          help"
echo ""
echo "------------------------------------------------------------------------"
}


printHELP1 ()
{
    printf "     $(tput bold)%-25s$(tput sgr0)       Align Pyramid TT\n" "$0" 
}



# Transform long options to short ones
singlelinehelp=0
for arg in "$@"; do
  shift
  case "$arg" in
    "--help") set -- "$@" "-h" ;;
    "--help1") 
set -- "$@" "-h" 
singlelinehelp=1;
;;
    *)        set -- "$@" "$arg"
  esac
done


while getopts :h FLAG; do
  case $FLAG in
    h)  #show help
      if [ "$singlelinehelp" -eq "0" ]; then
      printHELP
      else
      printHELP1
      fi
      exit
      ;;
    \?) #unrecognized option - show help
      echo -e \\n"Option -${BOLD}$OPTARG${NORM} not allowed."
      printHELP
      ;;
  esac
done

shift $((OPTIND-1)) 







if [ "$1" = "help" ] || [ "$#" -ne $NBARGS ]; then
if [ "$#" -ne $NBARGS ]; then
    echo "$(tput setaf 1)$(tput bold) Illegal number of parameters ($NBARGS params required, $# entered) $(tput sgr0)"
fi
printHELP
        exit
fi



loopnb=$( head -1 LOOPNUMBER )

pname0=$0
pname=${pname0#"./"}-$loopnb

echo "$pname"
echo $$ > "pid_${pname}.txt"


echo "readshmim aol${loopnb}_wfsdark" > alignTTpyr-startup.txt
echo "cp aol${loopnb}_wfsdark wfsdark" >> alignTTpyr-startup.txt
echo "readshmim aol${loopnb}_wfs" >> alignTTpyr-startup.txt
echo "scexaopywfsttalign aol${loopnb}_wfs" >> alignTTpyr-startup.txt
#echo "exit" >> ${pname}-fifo

./AOloopControl -n $pname --startup="alignTTpyr-startup.txt" -f ${pname}-fifo



