#!/bin/bash


# number of arguments to script
NBARGS=0


# ======================= PROCESS NAME =================================
pname=`echo "$0" | sed "s/\.\///g"`






function printHELP {
echo "------------------------------------------------------------------------"
echo "$(tput bold) $pname : PROCESS TELEMETRY, make PSDs  $(tput sgr 0)"
echo "------------------------------------------------------------------------"
echo "  Make open and close loop PSDs"
echo "   "
echo " $(tput bold)USAGE:$(tput sgr 0)"
echo "     $0 [-h]"
echo ""
echo " $(tput bold)OPTIONS:$(tput sgr 0)"
echo "     $(tput bold)-h$(tput sgr 0)          help"
echo ""
echo " $(tput bold)INPUT:$(tput sgr 0)"
echo "    PredictiveControl/modeval_ol.fits"
echo "    PredictiveControl/modeval_cl.fits"
echo ""
echo " $(tput bold)OUTPUT:$(tput sgr 0)"
echo "    PredictiveControl/psd_ol.fits"
echo "    PredictiveControl/psd_cl.fits"
echo "    PredictiveControl/psd_ol.txt"
echo "    PredictiveControl/psd_cl.txt"
echo ""
echo "------------------------------------------------------------------------"
}


printHELP1 ()
{
    printf "     $(tput bold)%-25s$(tput sgr0)       Process telemetry: create open and closed loop PSDs\n" "$0" 
}





# Transform long options to short ones
singlelinehelp=0
for arg in "$@"; do
  shift
  case "$arg" in
    "--help") set -- "$@" "-h" ;;
    "--help1") 
set -- "$@" "-h" 
singlelinehelp=1;
;;
    *)        set -- "$@" "$arg"
  esac
done




# ================= OPTIONS =============================

while getopts :h FLAG; do
  case $FLAG in
    h)  #show help
      if [ "$singlelinehelp" -eq "0" ]; then
      printHELP
      else
      printHELP1
      fi
      exit
      ;;
    \?) #unrecognized option - show help
      echo -e \\n"Option -${BOLD}$OPTARG${NORM} not allowed."
      printHELP
      ;;
  esac
done

shift $((OPTIND-1))  





if [ "$1" = "help" ] || [ "$#" -ne $NBARGS ]; then
if [ "$#" -ne $NBARGS ]; then
    echo "$(tput setaf 1)$(tput bold) Illegal number of parameters ($NBARGS params required, $# entered) $(tput sgr 0)"
fi
printHELP
        exit
fi




loopnb=$( head -1 LOOPNUMBER )




./AOloopControl << EOF
loadfits "./PredictiveControl/modeval_ol.fits" im
im3Dto2D im
imswapaxis2D im im1
do1Drfft im1 imcc
c2ap imcc ima imp
imi=ima*ima
savefits imi "!./PredictiveControl/psd_ol.fits"
im2ascii imi "./PredictiveControl/psd_ol.txt"
listim
exitCLI
EOF



./AOloopControl << EOF
loadfits "./PredictiveControl/modeval_cl.fits" im
im3Dto2D im
imswapaxis2D im im1
do1Drfft im1 imcc
c2ap imcc ima imp
imi=ima*ima
savefits imi "!./PredictiveControl/psd_cl.fits"
im2ascii imi "./PredictiveControl/psd_cl.txt"
listim
exitCLI
EOF

