#!/bin/bash


# number of arguments to script
NBARGS=8



#streamWFScube="$1"
#streamPSFcube="$2"
#selFrac="$3"

#x0="$4"
#x1="$5"
#y0="$6"
#y1="$7"
#evalMode="$8" 


# SCRIPT ARGUMENTS (mandatory)
# syntax: "name:type(s)/test(s):description"
MSarg+=( "logdir:string:telemetry directory" )
MSarg+=( "streamWFS:string:WFS stream" ) 
MSarg+=( "streamPSF:string:PSF stream" ) 
MSarg+=( "selfrac:float:selection fraction" )
MSarg+=( "x0:long:selection window x start" )
MSarg+=( "x1:long:selection window x end" )
MSarg+=( "y0:long:selection window y start" )
MSarg+=( "y1:long:selection window x end" )
MSarg+=( "emode:long:Evaluation mode" )


# load arguments
logdirectory="${inputMSargARRAY[0]}"
streamWFS="${inputMSargARRAY[1]}"
streamPSF="${inputMSargARRAY[2]}"
selFrac="${inputMSargARRAY[3]}"
windowx0="${inputMSargARRAY[4]}"
windowx1="${inputMSargARRAY[5]}"
windowy0="${inputMSargARRAY[6]}"
windowy1="${inputMSargARRAY[7]}"
evalMode="${inputMSargARRAY[8]}"






# ======================= PROCESS NAME =================================
pname=`echo "$0" | sed "s/\.\///g"`
echo "pname = $pname"


function printHELP {
echo "------------------------------------------------------------------------"
echo "$(tput bold) $pname : SELECT WFS FRAMES FROM PSF TELEMETRY $(tput sgr0)"
echo "------------------------------------------------------------------------"
echo "  Select WFS frames from times at which PSF is best"
echo "  Requires synchronized data cubes created by cacao-syncStreams"
echo "   "
echo " $(tput bold)USAGE:$(tput sgr0)"
echo "     $0 [-h] <streamWFScube> <streamPSFcube> <Selection fraction> <x0> <x1> <y0> <y1> <Mode>"
echo ""
echo " $(tput bold)OPTIONS:$(tput sgr0)"
echo "     $(tput bold)-h$(tput sgr0)          help"
echo "     $(tput bold)-a$(tput sgr0)          alpha norm (default=2.0)"
echo ""
echo " $(tput bold)INPUT:$(tput sgr0)"
echo "     <streamWFScube>     WFC stream name"
echo "     <streamPSFcube>     PSF stream name"
echo "     <x0><x1><y0><y1>    PSF evaluation window"
echo "     <evalMode>          0: optimize flux concentration"
echo "                         1: maximize flux"
echo "                         2: minimize flux"
echo ""
echo " $(tput bold)EXAMPLE:$(tput sgr0)"
echo "     $0 aol0_wfsim.sync.fits aol0_psf.sync.fits 0 64 0 64 0"
echo ""
echo " $(tput bold)OUTPUT:$(tput sgr0)"
echo "     impsfbest.fits     Average of selected PSF frames"
echo "     impsfall.fits      Average of all PSF frames"
echo "     imwfsbest.fits     Average of selected WFS frames"
echo "     imwfsall.fits      Average of all WFS frames"
echo ""
echo "------------------------------------------------------------------------"
}



printHELP1 ()
{
	printf "%20s       Select WFS frames from best PSF frames\n" "$0" 
}



# ================= OPTIONS =============================




# Transform long options to short ones
singlelinehelp=0
for arg in "$@"; do
  shift
  case "$arg" in
    "--help") set -- "$@" "-h" ;;
    "--help1") 
set -- "$@" "-h" 
singlelinehelp=1;
;;
    *)        set -- "$@" "$arg"
  esac
done



ALPHAnorm="2.0"

#Parse command line flags
#If an option should be followed by an argument, it should be followed by a ":".
#Notice there is no ":" after "h". The leading ":" suppresses error messages from
#getopts. This is required to get unrecognized option code to work.

while getopts :hH:a: FLAG; do
  case $FLAG in
    H) # detailed help
    if [ "$OPTARG" == "cf" ]; then
    printHELP_confFILES
    exit
    fi
    echo "ERROR: choice $OPTARG not recognized"
    exit
    ;;
    h)  #show help
      if [ "$singlelinehelp" -eq "0" ]; then
      printHELP
      else
      printHELP1
      fi
      exit
      ;;
    a)
    ALPHAnorm="$OPTARG"
    ;;
    \?) #unrecognized option - show help
      echo -e \\n"Option -${BOLD}$OPTARG${NORM} not allowed."
      printHELP
      ;;
  esac
done

shift $((OPTIND-1))  #This tells getopts to move on to the next argument.

### End getopts code ###








if [ "$1" = "help" ] || [ "$#" -ne $NBARGS ]; then
if [ "$#" -ne $NBARGS ]; then
    echo "$(tput setaf 1)$(tput bold) Illegal number of parameters ($NBARGS params required, $# entered) $(tput sgr0)"
fi
printHELP
        exit
fi





cacao << EOF
loadfits "$streamWFScube" imwfsC
loadfits "$streamPSFcube" impsfC

aolperfselwfsfpsf imwfsC impsfC $selFrac $x0 $x1 $y0 $y1 $evalMode $ALPHAnorm

savefits imwfsbest "!imwfsbest.fits"
savefits imwfsall "!imwfsall.fits"

savefits impsfbest "!impsfbest.fits"
savefits impsfall "!impsfall.fits"

listim
exit
EOF
