#! /bin/bash




NBARGS=2
pname=`echo "$0" | sed "s/\.\///g"`

function printHELP {
echo "------------------------------------------------------------------------"
echo "$(tput bold) $pname : Automatic gain tuning$(tput sgr0)"
echo "------------------------------------------------------------------------"
echo "  Automatic gain tuning"
echo "   "
echo " $(tput bold)USAGE:$(tput sgr0)"
echo "     $0 [-h] <updateGain> <NBsamples>"
echo ""
echo " $(tput bold)OPTIONS:$(tput sgr0)"
echo "     $(tput bold)-h$(tput sgr0)          help"
echo ""
echo " $(tput bold)INPUT:$(tput sgr0)"
echo "     <updateGain>     update coefficient"
echo "     <NBsamples>      Number of telemetry samples per iteration"
echo ""
echo " $(tput bold)OUTPUT:$(tput sgr0)"
echo ""
echo " $(tput bold)NOTES:$(tput sgr0)"
echo ""
echo "------------------------------------------------------------------------"
}


printHELP1 ()
{
    printf "     $(tput bold)%-25s$(tput sgr0)       Automatic gain tuning\n" "$0" 
}




# Transform long options to short ones
singlelinehelp=0
for arg in "$@"; do
  shift
  case "$arg" in
    "--help") set -- "$@" "-h" ;;
    "--help1") 
set -- "$@" "-h" 
singlelinehelp=1;
;;
    *)        set -- "$@" "$arg"
  esac
done


while getopts :h FLAG; do
  case $FLAG in
    h)  #show help
      if [ "$singlelinehelp" -eq "0" ]; then
      printHELP
      else
      printHELP1
      fi
      exit
      ;;
    \?) #unrecognized option - show help
      echo -e \\n"Option -${BOLD}$OPTARG${NORM} not allowed."
      printHELP
      ;;
  esac
done

shift $((OPTIND-1)) 







if [ "$1" = "help" ] || [ "$#" -ne $NBARGS ]; then
if [ "$#" -ne $NBARGS ]; then
    echo "$(tput setaf 1)$(tput bold) Illegal number of parameters ($NBARGS params required, $# entered) $(tput sgr0)"
fi
printHELP
        exit
fi










loopnb=$( head -1 LOOPNUMBER )
csetname="aol${loopnb}RT"


./AOloopControl -n $pname << EOF
csetpmove aol0RT 
csetpmove ${csetname}
aolautotunegains $loopnb aol${loopnb}_autogain $1 $2
exitCLI
EOF


