#! /bin/bash



# number of arguments to script
NBARGS=0
loopnb=$( head -1 LOOPNUMBER 2> /dev/null)

#pname0=`basename $0`
#pname=$pname0-$loopnb

pname=aol${loopnb}run

function printHELP {
echo "------------------------------------------------------------------------"
echo "$(tput bold) $pname : Run AO control loop $(tput sgr0)"
echo "------------------------------------------------------------------------"
echo "  Run AO control loop"
echo "   "
echo " $(tput bold)USAGE:$(tput sgr0)"
echo "     $0 [-h]"
echo ""
echo " $(tput bold)OPTIONS:$(tput sgr0)"
echo "     $(tput bold)-h$(tput sgr0)          help"
echo ""
echo "------------------------------------------------------------------------"
}


printHELP1 ()
{
    printf "     $(tput bold)%-25s$(tput sgr0)       Run AO control loop\n" "$0" 
}




# Transform long options to short ones
singlelinehelp=0
for arg in "$@"; do
  shift
  case "$arg" in
    "--help") set -- "$@" "-h" ;;
    "--help1") 
set -- "$@" "-h" 
singlelinehelp=1;
;;
    *)        set -- "$@" "$arg"
  esac
done


while getopts :h FLAG; do
  case $FLAG in
    h)  #show help
      if [ "$singlelinehelp" -eq "0" ]; then
      printHELP
      else
      printHELP1
      fi
      exit
      ;;
    \?) #unrecognized option - show help
      echo -e \\n"Option -${BOLD}$OPTARG${NORM} not allowed."
      printHELP
      ;;
  esac
done

shift $((OPTIND-1)) 







if [ "$1" = "help" ] || [ "$#" -ne $NBARGS ]; then
if [ "$#" -ne $NBARGS ]; then
    echo "$(tput setaf 1)$(tput bold) Illegal number of parameters ($NBARGS params required, $# entered) $(tput sgr0)"
fi
printHELP
        exit
fi






execname="./AOloopControl"

if [ ! -f "LOOPNUMBER" ]; then
echo ""
echo "ERROR: file LOOPNUMBER is missing"
echo " File LOOPNUMBER must exist and contain a integer"
echo ""
exit
fi


confnb=$( head -1 ./conf/conf_CONFNUMBER.txt )

csetname="aol${loopnb}RT"


# Reload/update FITS->SHM if needed
Fits2shm -c -p aol${loopnb}_ respM
Fits2shm -c -p aol${loopnb}_ DMmodes
Fits2shm -c -p aol${loopnb}_ contrM

OMP_NUM_THREADS=4 $execname -n $pname << EOF
csetpmove aol0RT
csetpmove ${csetname}
cacao.aolnb $loopnb
cacao.aolrun
exitCLI
EOF

