#!/bin/bash



# number of arguments to script
NBARGS=2

# ======================= PROCESS NAME =================================
pname=`echo "$0" | sed "s/\.\///g"`





function printHELP {
echo "------------------------------------------------------------------------"
echo "$(tput bold) $pname : MEASURE SYSTEM RESPONSE LATENCY $(tput sgr0)"
echo "------------------------------------------------------------------------"
echo "  Measures latency excluding WFS reconstruction time"
echo "   "
echo " $(tput bold)USAGE:$(tput sgr0)"
echo "     $0 [-h] <ampl> <NBiter>"
echo ""
echo " $(tput bold)OPTIONS:$(tput sgr0)"
echo "     $(tput bold)-h$(tput sgr0)          help"
echo ""
echo " $(tput bold)INPUT:$(tput sgr0)"
echo "     <ampl>       Poke amplitude [um]"
echo "     <NBiter>     Number of iterations"
echo ""
echo ""
echo "------------------------------------------------------------------------"
}


printHELP1 ()
{
    printf "     $(tput bold)%-25s$(tput sgr0)       Measure AO system response latency\n" "$0" 
}






# Transform long options to short ones
singlelinehelp=0
for arg in "$@"; do
  shift
  case "$arg" in
    "--help") set -- "$@" "-h" ;;
    "--help1") 
set -- "$@" "-h" 
singlelinehelp=1;
;;
    *)        set -- "$@" "$arg"
  esac
done








while getopts :h FLAG; do
  case $FLAG in
    h)  #show help
      if [ "$singlelinehelp" -eq "0" ]; then
      printHELP
      else
      printHELP1
      fi
      exit
    ;;
    \?) #unrecognized option - show help
      echo -e \\n"Option -${BOLD}$OPTARG${NORM} not allowed."
      printHELP
      ;;
  esac
done

shift $((OPTIND-1))  





if [ "$1" = "help" ] || [ "$#" -ne $NBARGS ]; then
if [ "$#" -ne $NBARGS ]; then
    echo "$(tput setaf 1)$(tput bold) Illegal number of parameters ($NBARGS params required, $# entered) $(tput sgr0)"
fi
printHELP
        exit
fi




loopnb=$( head -1 LOOPNUMBER )


./AOloopControl -n aol${loopnb}latency << EOF
readshmim aol${loopnb}_wfsim
readshmim aol${loopnb}_dmC
aoltestlat aol${loopnb}_dmC aol${loopnb}_wfsim $1 $2
savefits _testwfsc "!./timingstats/test_latencyC.fits"
exitCLI
EOF
