language: C

before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq libcfitsio3 libcfitsio3-dev libreadline6-dev libncurses5-dev libfftw3-dev libgsl0-dev flex bison

script:
- mkdir _build
- cd _build
- cmake ..
- make
- sudo make install

notification:
        webhook:
                url: https://webhooks.gitter.im/e/072068cc9fea29c15521
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always

