language: C

before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq libcfitsio3 libcfitsio3-dev libreadline6-dev libncurses5-dev libfftw3-dev libgsl0-dev flex bison automake autoconf libtool autotools-dev check

script:
- touch src/Makefile.am.add
- cp configure.ac.cacao configure.ac
- autoreconf -vif
- ./configure
- make
- make install

