--- 
before_install: 
  - "sudo apt-get update -qq"
  - "sudo apt-get install -qq libcfitsio5 libcfitsio3-dev libreadline6-dev libncurses5-dev libfftw3-dev libgsl0-dev flex bison"
language: C
notification: 
  webhook: 
    on_failure: always
    on_start: never
    on_success: change
    url: "https://webhooks.gitter.im/e/072068cc9fea29c15521"
script: 
  - "mkdir _build"
  - "cd _build"
  - "cmake .."
  - make
  - "sudo make install"



