dist: bionic

language: C

before_install: 
  - "sudo apt-get update -qq"
  - "sudo apt-get install -qq libcfitsio-dev libreadline6-dev libncurses5-dev libfftw3-dev libgsl0-dev flex bison"


notification: 
  webhook: 
    on_failure: always
    on_start: never
    on_success: change
    url: "https://webhooks.gitter.im/e/072068cc9fea29c15521"

before_script:
- pwd
- ls -l
- echo "tmpfs /milk/shm tmpfs rw,nosuid,nodev" | sudo tee -a /etc/fstab
- sudo mkdir -p /milk/shm
- sudo mount /milk/shm
- git clone --recursive https://github.com/milk-org/milk-package milk
- cd milk
- mkdir _build
- cd _build
- cmake ..
- sudo make install
- ls -l /usr/local/
- sudo ln -s /usr/local/milk-1.01 /usr/local/milk
- export MILK_ROOT=${HOME}/src/milk
- export MILK_INSTALLDIR=/usr/local/milk
- export PATH=${PATH}:${MILK_INSTALLDIR}/bin
- export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:${MILK_INSTALLDIR}/lib/pkgconfig
- export MILK_SHM_DIR=/milk/shm
- echo "/usr/local/milk/lib" > milklibs.conf
- sudo mv milklibs.conf /etc/ld.so.conf.d/
- sudo ldconfig
- cd


script: 
- pwd
- ls -l
- more build.sh




