dist: bionic

language: C

before_install: 
- sudo apt-get update -qq
- sudo apt-get install -qq libcfitsio-dev libreadline6-dev libncurses5-dev libfftw3-dev libgsl0-dev flex bison
- echo "tmpfs /milk/shm tmpfs rw,nosuid,nodev" | sudo tee -a /etc/fstab
- sudo mkdir -p /milk/shm
- sudo mount /milk/shm
- git clone -b dev --recursive https://github.com/milk-org/milk-package milk
- mkdir milk/_build
- pushd milk/_build
- cmake .. -DEXTRAMODULES="milk_module_example" -DINSTALLMAKEDEFAULT=ON
- sudo make install
- export MILK_ROOT=${HOME}/src/milk
- export MILK_INSTALLDIR=/usr/local/milk
- export PATH=${PATH}:${MILK_INSTALLDIR}/bin
- export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:${MILK_INSTALLDIR}/lib/pkgconfig
- export MILK_SHM_DIR=/milk/shm
- echo "/usr/local/milk/lib" > milklibs.conf
- sudo mv milklibs.conf /etc/ld.so.conf.d/
- sudo ldconfig
- popd

notification: 
  webhook: 
    on_failure: always
    on_start: never
    on_success: change
    url: "https://webhooks.gitter.im/e/072068cc9fea29c15521"

before_script:


script:
- pwd
- mkdir _build
- cd _build
- cmake .. -DINSTALLMAKEDEFAULT=ON
- make 
- sudo make install
- echo "/usr/local/cacao/lib" > cacaolibs.conf
- sudo mv cacaolibs.conf /etc/ld.so.conf.d/
- sudo ldconfig
- export PATH=${PATH}:/usr/local/cacao/bin
- ctest -D Experimental




