#!/usr/bin/env bash

FPSKWname="CACAO_FPSPROC_ACQLINCMRM"

FPSKWval="NULL"
if [ ! -z "${CACAO_FPSPROC_ACQLINCMRM+x}" ]; then
	FPSKWval="$CACAO_FPSPROC_ACQLINCMRM"
fi


# FPS name
fpsname="acqlin_cmRM"
fpsarg0="${CACAO_LOOPNUMBER}"

# FPS full name
fpsfname="${fpsname}-${fpsarg0}"

# function call
fpsfcall="cacaoac.aolmeaslWFSrespC"

# short description
fpsdescr="Acquire Linear Response Matrix on Control Modes"



function fpsentry_addmodules() {
	echo "no module to be added"
}

function fpsentry_addcmds() {
	CACAO_CMDMINDEX=2
	addfpscmd "setval ${fpsfname}.AOloopindex ${CACAO_LOOPNUMBER}"

	addfpscmd "setval ${fpsfname}.FPS_mlat mlat-${CACAO_LOOPNUMBER}"
	addfpscmd "setval ${fpsfname}.FPS_DMcomb DMch2disp-cm${CACAO_DMINDEX}"


	# default startup values
	addfpscmd "setval ${fpsfname}.normalize OFF"
	addfpscmd "setval ${fpsfname}.Hpoke OFF"
	addfpscmd "setval ${fpsfname}.autoTiming ON"
	addfpscmd "setval ${fpsfname}.compDMmask OFF"
	addfpscmd "setval ${fpsfname}.compMpoke OFF"

	addfpscmd "setval ${fpsfname}.timing.NBave 1"
	addfpscmd "setval ${fpsfname}.timing.NBcycle 4"
	addfpscmd "setval ${fpsfname}.timing.NBinnerCycle 1"
	addfpscmd "setval ${fpsfname}.timing.NBexcl 0"


	addfpscmd "setval ${fpsfname}.fn_pokeC respM_LOmodes.fits"

	addfpscmd "setval ${fpsfname}.MaskMode OFF"

	addfpscmd "setval ${fpsfname}.exec.RMdecode cacaobin/cacao-NULL"
	addfpscmd "setval ${fpsfname}.exec.mkDMWFSmasks cacaobin/cacao-NULL"
	addfpscmd "setval ${fpsfname}.exec.mkDMslaveact cacaobin/cacao-NULL"
	addfpscmd "setval ${fpsfname}.exec.mkLODMmodes cacaobin/cacao-NULL"
}


source milk-fpslist-addentry

