#!/usr/bin/env bash

# This script uses milk-argparse
# See template milk-scriptexample in module milk_module_example for template and instructions


# script 1-line description
MSdescr="Deploy a cacao loop example from source code"



# Extended description
conflist=$( ls $MILK_ROOT/plugins/cacao-src/AOloopControl/examples | grep "\-conf" | sed 's/\-[^-]*$//')


MSextdescr="Configuration is loaded from cacao source code

Available configurations :

$conflist

"

# standard configuration
# location ./scripts/
source milk-script-std-config

# prerequisites
#
RequiredCommands=( milk tmux cacao )
RequiredFiles=()
RequiredDirs=( ${MILK_ROOT} )



# SCRIPT MANDATORY ARGUMENTS
# syntax: "name:type(s)/test(s):description"
#
MSarg+=( "cacaoconfname:string:configuration name" )


# SCRIPT OPTIONS
# syntax: "short:long:functioncall:args[types]:description"
#
FORCE="0"
MSopt+=( "f:force:set_force::force deployment" )
function set_force() {
	FORCE="1"
}

CPCONF="ON"
RUNCONF="ON"

MSopt+=( "c:copy:set_copy::copy configuration, do not run it" )
function set_copy() {
	RUNCONF="OFF"
}


MSopt+=( "r:run:set_run::run configuration, do not copy it" )
function set_run() {
	CPCONF="OFF"
}




# parse arguments
source milk-argparse
cacaoconfname="${inputMSargARRAY[0]}"


echo "Configuration ${cacaoconfname}"


# Download example
confsrcdir="${MILK_ROOT}/plugins/cacao-src/AOloopControl/examples/${cacaoconfname}-conf"


if [ ${CPCONF} == "ON" ]; then

if [[ -d "$confsrcdir" ]]
then
	rsync -au --progress ${MILK_ROOT}/plugins/cacao-src/AOloopControl/examples/${cacaoconfname}-conf .
else
	echo "ERROR: Cannot find directory ${confsrcdir}"
	exit
fi


fi





if [ ${RUNCONF} == "ON" ]; then


nbtask=$( grep -c '^[^#]' ${cacaoconfname}-conf////tasklist.txt )
echo "${nbtask} TASKS"



# Run cacao task manager


cacao-task-manager -X ${nbtask} ${cacaoconfname}


source ${cacaoconfname}-conf/cacaovars.bash

echo ""
echo "CACAO_LOOPROOTDIR = ${CACAO_LOOPROOTDIR}"
echo "CACAO_LOOPRUNDIR = ${CACAO_LOOPRUNDIR}"

cp ${cacaoconfname}-conf/aorun-* ./${CACAO_LOOPROOTDIR}/

fi
