#!/usr/bin/env bash

AOLOOPNUMBER=0

# Arguments:
# Calib name



ARCHDIR="AOcalibs/$1"

if [[ -d "${ARCHDIR}" ]]; then

# remove existing streams
milk-shmimpurge aol${AOLOOPNUMBER}_modesWFS
milk-shmimpurge aol${AOLOOPNUMBER}_DMmodes
milk-shmimpurge aol${AOLOOPNUMBER}_wfsref
milk-shmimpurge aol${AOLOOPNUMBER}_wfsmask
milk-shmimpurge aol${AOLOOPNUMBER}_wfsmap
milk-shmimpurge aol${AOLOOPNUMBER}_dmmask
milk-shmimpurge aol${AOLOOPNUMBER}_dmslaved
milk-shmimpurge aol${AOLOOPNUMBER}_zrespM
milk-shmimpurge aol${AOLOOPNUMBER}_LOrespM
milk-shmimpurge aol${AOLOOPNUMBER}_LODMmodes

milk <<EOF
loadfits "${ARCHDIR}/aol${AOLOOPNUMBER}_modesWFS.fits" aolmWFS
cpsh aolmWFS aol${AOLOOPNUMBER}_modesWFS

loadfits "${ARCHDIR}/aol${AOLOOPNUMBER}_DMmodes.fits" aolmDM
cpsh aolmDM  aol${AOLOOPNUMBER}_DMmodes

loadfits "${ARCHDIR}/aol${AOLOOPNUMBER}_wfsref.fits" aolwfsref
cpsh aolwfsref aol${AOLOOPNUMBER}_wfsref

loadfits "${ARCHDIR}/aol${AOLOOPNUMBER}_wfsmask.fits" aolwfsmask
cpsh aolwfsmask aol${AOLOOPNUMBER}_wfsmask


loadfits "${ARCHDIR}/aol${AOLOOPNUMBER}_wfsmap.fits" aolwfsmap
cpsh aolwfsmap aol${AOLOOPNUMBER}_wfsmap

loadfits "${ARCHDIR}/aol${AOLOOPNUMBER}_dmmask.fits" aoldmmask
cpsh aoldmmask aol${AOLOOPNUMBER}_dmmask

loadfits "${ARCHDIR}/aol${AOLOOPNUMBER}_dmslaved.fits" aoldmslaved
cpsh aoldmslaved aol${AOLOOPNUMBER}_dmslaved

loadfits "${ARCHDIR}/aol${AOLOOPNUMBER}_zrespM.fits" aolzrespM
cpsh aolzrespM aol0_zrespM

loadfits "${ARCHDIR}/aol${AOLOOPNUMBER}_LOrespM.fits" aolLOrespM
cpsh aolLOrespM aol${AOLOOPNUMBER}_LOrespM

loadfits "${ARCHDIR}/aol${AOLOOPNUMBER}_LODMmodes.fits" aolLODMmodes
cpsh aolLODMmodes aol${AOLOOPNUMBER}_LODMmodes

exitCLI
EOF

else
    echo "DIRECTORY DOES NOT EXIST"
fi
