#!/usr/bin/env bash

FPSKWname="CACAO_FPSPROC_MVMGPU_DM2MVAL"

FPSKWval="NULL"
if [ ! -z "${CACAO_FPSPROC_MVMGPU_DM2MVAL+x}" ]; then
	FPSKWval="$CACAO_FPSPROC_MVMGPU_DM2MVAL"
fi


# FPS name
fpsname="dm2mval"
fpsarg0="${CACAO_LOOPNUMBER}"

# FPS full name
fpsfname="${fpsname}-${fpsarg0}"

# function call
fpsfcall="milk-fpsexec-linalg-MVMextract"

# short description
fpsdescr="MVM-compute modes values from DM"



function fpsentry_addmodules() {
	echo "+milklinalgebra" >> fpslist.txt
}

function fpsentry_addcmds() {
    addfpscmd "setval ${fpsfname}.procinfo.loopcntMax -1"
    addfpscmd "setval ${fpsfname}.procinfo.triggermode 3"
    addfpscmd "setval ${fpsfname}.procinfo.triggersname aol${CACAO_LOOPNUMBER}_dmC"


    addfpscmd "setval ${fpsfname}.insname aol${CACAO_LOOPNUMBER}_dmC"
    addfpscmd "setval ${fpsfname}.immodes aol${CACAO_LOOPNUMBER}_matDM2mval"
    # filtered modevalDM
    addfpscmd "setval ${fpsfname}.outcoeff aol${CACAO_LOOPNUMBER}_modevalDMf"

	# is using imWFS2 as input, no need to subtract reference
    addfpscmd "setval ${fpsfname}.option.sname_refin NULL"

    addfpscmd "setval ${fpsfname}.option.sname_refout NULL"

    addfpscmd "setval ${fpsfname}.outinit ON"

    addfpscmd "setval ${fpsfname}.GPUindex 0"

    addfpscmd "setval ${fpsfname}.option.PROCESS ON"
    addfpscmd "setval ${fpsfname}.option.TRACEMODE OFF"
    addfpscmd "setval ${fpsfname}.option.MODENORM OFF"

    addfpscmd "setval ${fpsfname}.option.twait 0"
}



source milk-fpslist-addentry
