#!/usr/bin/env bash

if [ "$1" = "-hs" ]; then
	echo "List cacao commands on system"
	exit 1
fi


CMDLIST=$(compgen -c "cacao-" | sort -u )

GREEN='\033[0;32m'
NC='\033[0m' # No Color

echo "LIST OF CACAO COMMANDS :"

for cmd in $CMDLIST; do

	helpline=$( $cmd -hs | head -n 1 )
	printf "	${GREEN}%-32s${NC}  %s\n" "$cmd" "$helpline"

done


