#!/usr/bin/env bash


MSdescr="launch cacao logging"

MSextdescr="launch cacao logging

Launch at beginning of each UT day.

Creates log directory ../logdir-${CACAO_LOOPNAME} if it does not exist.
Note that the directory may be created as a symlink to system log directory prior to running this command.

Starts FPS log process within a tmux session 

Starts cacao log -> 
"


source milk-script-std-config

# check and load cacaovars
source cacao-check-cacaovars


RequiredCommands=( cacao tmux )
RequiredPipes=()
RequiredFiles=()
RequiredDirs=()

source milk-argparse


# log directory
mkdir -p ../logdir-${CACAO_LOOPNAME}
mkdir -p ../logdir-${CACAO_LOOPNAME}/$(date -u +'%Y%m%d')

# make local dir pointing to upstream log
rm -rf logdir
echo "ln -sf $(pwd)/../logdir-${CACAO_LOOPNAME}/$(date -u +'%Y%m%d') logdir"
ln -sf $(pwd)/../logdir-${CACAO_LOOPNAME}/$(date -u +'%Y%m%d') logdir



tmuxname="cacaolog-${CACAO_LOOPNAME}"
# kill session if it does not exist
set +e
tmux send-keys -t ${tmuxname} C-c
tmux send-keys -t ${tmuxname} "exit" C-m
tmux kill-session -t ${tmuxname}
sleep 1
set -e

tmux new-session -d -s ${tmuxname}
tmux send-keys -t ${tmuxname} "cacao-fpsctrl-log -r" C-m
sleep 1




# start windows
echo "Connecting to tmux session fpsCTRLlog-cacao-${CACAO_LOOPNAME}"
xterm -geometry 160x40 -fg white -bg black -xrm 'XTerm.vt100.allowTitleOps: false' -T "fpsCTRLlog-${CACAO_LOOPNAME} (CTRL+B D to exit)" -e "tmux ls| grep fpsCTRLlog-cacao-${CACAO_LOOPNAME}; sleep 1; tmux a -t fpsCTRLlog-cacao-${CACAO_LOOPNAME}; sleep 1" &

xterm -geometry 80x10 -fg white -bg black -xrm 'XTerm.vt100.allowTitleOps: false' -T "Operatorlog-${CACAO_LOOPNAME}-input (CTRL+C to exit)" -e "cacao-log -k \"OPNOTES\" -i; sleep 1" &

xterm -geometry 80x10 -fg white -bg black -xrm 'XTerm.vt100.allowTitleOps: false' -T "Weatherlog-${CACAO_LOOPNAME}-input (CTRL+C to exit)" -e "cacao-log -k \"WEATHER\" -i; sleep 1" &


logdname="logdir"
echo "LOG DIRNAME = ${logdname}"
mkdir -p ${logdname}
logfname="${logdname}/cacao.${CACAO_LOOPNAME}.log"
if [ ! -f ${logfname} ]; then
	echo "Creating file ${logfname}"
	touch ${logfname}
fi
echo "Message log : ${logfname}"
xterm -geometry 160x20 -fg white -bg black -xrm 'XTerm.vt100.allowTitleOps: false' -T "Operatorlog-${CACAO_LOOPNAME}-output (CTRL+C to exit)" -e "sleep 1; tail -f ${logfname}; sleep 1" &
