#!/usr/bin/env bash

if [ -f LOOPNUMBER ]; then
    AOLOOPNUMBER=$( head -1 LOOPNUMBER )
else
	echo "Error: no LOOPNUMBER file. Are we running this from the correct directory ?"
    exit
fi

# Arguments:
# Calib name


ARCHDIR="AOcalibs/$1"

mkdir -p ${ARCHDIR}


milk << EOF
readshmim aol${AOLOOPNUMBER}_modesWFS
saveFITS aol${AOLOOPNUMBER}_modesWFS "${ARCHDIR}/aol${AOLOOPNUMBER}_modesWFS.fits"

readshmim aol${AOLOOPNUMBER}_DMmodes
saveFITS aol${AOLOOPNUMBER}_DMmodes "${ARCHDIR}/aol${AOLOOPNUMBER}_DMmodes.fits"

readshmim aol${AOLOOPNUMBER}_wfsref
saveFITS aol${AOLOOPNUMBER}_wfsref "${ARCHDIR}/aol${AOLOOPNUMBER}_wfsref.fits"


readshmim aol${AOLOOPNUMBER}_wfsmask
saveFITS aol${AOLOOPNUMBER}_wfsmask "${ARCHDIR}/aol${AOLOOPNUMBER}_wfsmask.fits"

readshmim aol${AOLOOPNUMBER}_wfsmap
saveFITS aol${AOLOOPNUMBER}_wfsmap "${ARCHDIR}/aol${AOLOOPNUMBER}_wfsmap.fits"

readshmim aol${AOLOOPNUMBER}_dmmask
saveFITS aol${AOLOOPNUMBER}_dmmask "${ARCHDIR}/aol${AOLOOPNUMBER}_dmmask.fits"

readshmim aol${AOLOOPNUMBER}_dmslaved
saveFITS aol${AOLOOPNUMBER}_dmslaved "${ARCHDIR}/aol${AOLOOPNUMBER}_dmslaved.fits"

readshmim aol${AOLOOPNUMBER}_zrespM
saveFITS aol${AOLOOPNUMBER}_zrespM "${ARCHDIR}/aol${AOLOOPNUMBER}_zrespM.fits"

readshmim aol${AOLOOPNUMBER}_LOrespM
saveFITS aol${AOLOOPNUMBER}_LOrespM "${ARCHDIR}/aol${AOLOOPNUMBER}_LOrespM.fits"

readshmim aol${AOLOOPNUMBER}_LODMmodes
saveFITS aol${AOLOOPNUMBER}_LODMmodes "${ARCHDIR}/aol${AOLOOPNUMBER}_LODMmodes.fits"

exitCLI
EOF
