#!/usr/bin/env bash

# Arguments:
# Calib name


ARCHDIR="AOcalibs/$1"

mkdir -p ${ARCHDIR}


milk << EOF
readshmim aol0_modesWFS
saveFITS aol0_modesWFS "${ARCHDIR}/aol0_modesWFS.fits"

readshmim aol0_DMmodes
saveFITS aol0_DMmodes "${ARCHDIR}/aol0_DMmodes.fits"

readshmim aol0_wfsref
saveFITS aol0_wfsref "${ARCHDIR}/aol0_wfsref.fits"


readshmim aol0_wfsmask
saveFITS aol0_wfsmask "${ARCHDIR}/aol0_wfsmask.fits"

readshmim aol0_wfsmap
saveFITS aol0_wfsmap "${ARCHDIR}/aol0_wfsmap.fits"

readshmim aol0_dmmask
saveFITS aol0_dmmask "${ARCHDIR}/aol0_dmmask.fits"

readshmim aol0_dmslaved
saveFITS aol0_dmslaved "${ARCHDIR}/aol0_dmslaved.fits"

readshmim aol0_zrespM
saveFITS aol0_zrespM "${ARCHDIR}/aol0_zrespM.fits"

readshmim aol0_LOrespM
saveFITS aol0_LOrespM "${ARCHDIR}/aol0_LOrespM.fits"

readshmim aol0_LODMmodes
saveFITS aol0_LODMmodes "${ARCHDIR}/aol0_LODMmodes.fits"

exitCLI
EOF
