#!/usr/bin/env bash


MSdescr="Apply AO calibration"

MSextdescr="Load calibration to shared memory from filesystem
To be executed from loop rootdir"

source milk-script-std-config

# check and load cacaovars
source cacao-check-cacaovars
RequiredCommands=(milk)
RequiredPipes=()
RequiredFiles=()
RequiredDirs=(AOcalibs)

MSarg+=( "calibname:string:calibration name" )

MSopt+=( "w:wfsdiag:setwfsdiag::use WFS-diagonalized modes" )
WFSdiag="0"
function setwfsdiag() {
	echo "Using WFS-diagonalized modes"
	WFSdiag="1"
}


source milk-argparse

set +u
if [ "${EXITSTATUS}" = "1" ]; then
exit 1
fi
set -u



calib="${inputMSargARRAY[0]}"
echo "Calibration : ${calib}"






# Arguments:
# Calib name



ARCHDIR="AOcalibs/${calib}"

echo "Loop ${CACAO_LOOPNUMBER}: Loading calibration from ${ARCHDIR}"

if [[ -d "${ARCHDIR}" ]]; then


if [ "${WFSdiag}" = "1" ]; then

# wfsdiag.txt records which basis was loaded
echo 1 > $MILK_SHM_DIR/aol${CACAO_LOOPNUMBER}_calib_wfsdiag.txt

MILK_QUIET=1 milk << EOF

loadfits "${ARCHDIR}/aol${CACAO_LOOPNUMBER}_modesWFS_WFSdiag.fits" aolmWFS
imcpshm aolmWFS aol${CACAO_LOOPNUMBER}_modesWFS

loadfits "${ARCHDIR}/aol${CACAO_LOOPNUMBER}_DMmodes_WFSdiag.fits" aolmDM
imcpshm aolmDM  aol${CACAO_LOOPNUMBER}_DMmodes

exitCLI
EOF

else


# wfsdiag.txt records which basis was loaded
echo 0 > $MILK_SHM_DIR/aol${CACAO_LOOPNUMBER}_calib_wfsdiag.txt

MILK_QUIET=1 milk << EOF

loadfits "${ARCHDIR}/aol${CACAO_LOOPNUMBER}_modesWFS.fits" aolmWFS
imcpshm aolmWFS aol${CACAO_LOOPNUMBER}_modesWFS

loadfits "${ARCHDIR}/aol${CACAO_LOOPNUMBER}_DMmodes.fits" aolmDM
imcpshm aolmDM  aol${CACAO_LOOPNUMBER}_DMmodes

exitCLI
EOF

fi



MILK_QUIET=1 milk <<EOF

loadfits "${ARCHDIR}/aol${CACAO_LOOPNUMBER}_wfsref.fits" aolwfsref
imcpshm aolwfsref aol${CACAO_LOOPNUMBER}_wfsref

loadfits "${ARCHDIR}/aol${CACAO_LOOPNUMBER}_wfsmask.fits" aolwfsmask
imcpshm aolwfsmask aol${CACAO_LOOPNUMBER}_wfsmask


loadfits "${ARCHDIR}/aol${CACAO_LOOPNUMBER}_wfsmap.fits" aolwfsmap
imcpshm aolwfsmap aol${CACAO_LOOPNUMBER}_wfsmap

loadfits "${ARCHDIR}/aol${CACAO_LOOPNUMBER}_dmmask.fits" aoldmmask
imcpshm aoldmmask aol${CACAO_LOOPNUMBER}_dmmask

loadfits "${ARCHDIR}/aol${CACAO_LOOPNUMBER}_dmslaved.fits" aoldmslaved
imcpshm aoldmslaved aol${CACAO_LOOPNUMBER}_dmslaved

loadfits "${ARCHDIR}/aol${CACAO_LOOPNUMBER}_zrespM.fits" aolzrespM
imcpshm aolzrespM aol${CACAO_LOOPNUMBER}_zrespM

loadfits "${ARCHDIR}/aol${CACAO_LOOPNUMBER}_LOrespM.fits" aolLOrespM
imcpshm aolLOrespM aol${CACAO_LOOPNUMBER}_LOrespM

loadfits "${ARCHDIR}/aol${CACAO_LOOPNUMBER}_LODMmodes.fits" aolLODMmodes
imcpshm aolLODMmodes aol${CACAO_LOOPNUMBER}_LODMmodes

exitCLI
EOF

# record this calib as applied
# TODO: is there a standard logger we should invoke?
echo $(pwd)/${ARCHDIR} > $MILK_SHM_DIR/aol${CACAO_LOOPNUMBER}_calib_source.txt
echo $(date -u --iso-8601=seconds) > $MILK_SHM_DIR/aol${CACAO_LOOPNUMBER}_calib_loaded.txt
echo "$(date -u --iso-8601=seconds) APPLY ${calib}" >> AOcalibs/AOcalib-${CACAO_LOOPNUMBER}-log.txt


else
    echo "DIRECTORY DOES NOT EXIST"
fi
