#!/usr/bin/env bash


MSdescr="Archive current AO calibration"

MSextdescr="Copy current filesystem calibration to AOcalibs/<calibname>/ directory"

source milk-script-std-config

# check and load cacaovars
source cacao-check-cacaovars
RequiredCommands=(milk)
RequiredPipes=()
RequiredFiles=()
RequiredDirs=(AOcalibs)


MSarg+=( "calibname:string:calibration name" )

source milk-argparse

set +u
if [ "${EXITSTATUS}" = "1" ]; then
exit
fi
set -u




calib="${inputMSargARRAY[0]}"
echo "Calibration : ${calib}"



# Arguments:
# Calib name


ARCHDIR="AOcalibs/${calib}"

mkdir -p ${ARCHDIR}


MILK_QUIET=1 milk << EOF
readshmim aol${CACAO_LOOPNUMBER}_modesWFS
saveFITS aol${CACAO_LOOPNUMBER}_modesWFS "${ARCHDIR}/aol${CACAO_LOOPNUMBER}_modesWFS.fits"

readshmim aol${CACAO_LOOPNUMBER}_DMmodes
saveFITS aol${CACAO_LOOPNUMBER}_DMmodes "${ARCHDIR}/aol${CACAO_LOOPNUMBER}_DMmodes.fits"

readshmim aol${CACAO_LOOPNUMBER}_wfsref
saveFITS aol${CACAO_LOOPNUMBER}_wfsref "${ARCHDIR}/aol${CACAO_LOOPNUMBER}_wfsref.fits"


readshmim aol${CACAO_LOOPNUMBER}_wfsmask
saveFITS aol${CACAO_LOOPNUMBER}_wfsmask "${ARCHDIR}/aol${CACAO_LOOPNUMBER}_wfsmask.fits"

readshmim aol${CACAO_LOOPNUMBER}_wfsmap
saveFITS aol${CACAO_LOOPNUMBER}_wfsmap "${ARCHDIR}/aol${CACAO_LOOPNUMBER}_wfsmap.fits"

readshmim aol${CACAO_LOOPNUMBER}_dmmask
saveFITS aol${CACAO_LOOPNUMBER}_dmmask "${ARCHDIR}/aol${CACAO_LOOPNUMBER}_dmmask.fits"

readshmim aol${CACAO_LOOPNUMBER}_dmslaved
saveFITS aol${CACAO_LOOPNUMBER}_dmslaved "${ARCHDIR}/aol${CACAO_LOOPNUMBER}_dmslaved.fits"

readshmim aol${CACAO_LOOPNUMBER}_zrespM
saveFITS aol${CACAO_LOOPNUMBER}_zrespM "${ARCHDIR}/aol${CACAO_LOOPNUMBER}_zrespM.fits"

readshmim aol${CACAO_LOOPNUMBER}_LOrespM
saveFITS aol${CACAO_LOOPNUMBER}_LOrespM "${ARCHDIR}/aol${CACAO_LOOPNUMBER}_LOrespM.fits"

readshmim aol${CACAO_LOOPNUMBER}_LODMmodes
saveFITS aol${CACAO_LOOPNUMBER}_LODMmodes "${ARCHDIR}/aol${CACAO_LOOPNUMBER}_LODMmodes.fits"

exitCLI
EOF




echo "$(date -u --iso-8601=seconds) ARCHCURRENT ${calib}" >> AOcalibs/AOcalib-${CACAO_LOOPNUMBER}-log.txt
