#!/usr/bin/env bash

CACAOTASK_SCRIPT_FNAME=$0
source cacaotask-check # check environment

# ======================================================================
# PERFORM ACTIONS FOR THIS TASK
# ======================================================================
echo "LOOPNAME          : ${LOOPNAME}"
echo "CONFDIR           : ${CONFDIR}"



echo "CACAO_LOOPROOTDIR : ${CACAO_LOOPROOTDIR}"


mkdir -p ${CACAO_LOOPROOTDIR}

# check if successful
if [ "$?" = 0 ]; then
    cacaotask_RETURNCODE=${CACAOTASK_RUN_SUCCESS}
else
    cacaotask_RETURNCODE=${CACAOTASK_RUN_FAIL}
fi

# copy test configuration files to work directory
cp ${CONFDIR}/cacaovars.bash ${CACAO_LOOPROOTDIR}/cacaovars.${LOOPNAME}.bash
cp ${CONFDIR}/cacao-fpslistadd-* ${CACAO_LOOPROOTDIR}/

cp ${CONFDIR}/fpssetup.setval.conf ${CACAO_LOOPROOTDIR}/fpssetup.setval.${LOOPNAME}.conf

# ======================================================================
# WRITE CLEANUP SCRIPT FOR THIS TASK
# ======================================================================

# Inside cat <<EOT section :
# ${VAR} will be resolved prior to writing to destination
# \${VAR} will not be resolved, and will appear as ${VAR} in the destination
#
cat <<EOT >>  ${CLEANSCRIPT}

rm ${CACAO_LOOPROOTDIR}/cacaovars.${LOOPNAME}.bash
rm ${CACAO_LOOPROOTDIR}/fpssetup.setval.${LOOPNAME}.conf

read -p "REMOVING directory ./\${CACAO_LOOPROOTDIR}. Are you sure? " -n 1 -r
echo
if [[ \${REPLY} =~ ^[Yy]$ ]]
then
    rm -r ./\${CACAO_LOOPROOTDIR}
fi

EOT


# ======================================================================
# STORE OUTPUT ENVIRONMENT VARIABLES
# ======================================================================

# NEWVAR_INITSETUP=2
# echo "NEWVAR_INITSETUP=${NEWVAR_INITSETUP}" >> ${ENVOUTFILE}
