#!/usr/bin/env bash

FPSKWname="CACAO_FPSPROC_MODALFILTERING"

FPSKWval="NULL"
if [ ! -z "${CACAO_FPSPROC_MODALFILTERING+x}" ]; then
	FPSKWval="$CACAO_FPSPROC_MODALFILTERING"
fi


# FPS name
fpsname="mfilt"
fpsarg0="${CACAO_LOOPNUMBER}"

# FPS full name
fpsfname="${fpsname}-${fpsarg0}"

# function call
fpsfcall="cacao.modalfilter"

# short description
fpsdescr="Modal filtering"



function fpsentry_addmodules() {
	echo "no module to be added"
}

function fpsentry_addcmds() {
	addfpscmd "setval ${fpsfname}.procinfo.loopcntMax -1"
	addfpscmd "setval ${fpsfname}.procinfo.triggermode 3"
	addfpscmd "setval ${fpsfname}.procinfo.triggersname aol${CACAO_LOOPNUMBER}_modevalWFS"

	addfpscmd "setval ${fpsfname}.inmval aol${CACAO_LOOPNUMBER}_modevalWFS"
	addfpscmd "setval ${fpsfname}.outmval aol${CACAO_LOOPNUMBER}_modevalDM"
}



source milk-fpslist-addentry

