#!/usr/bin/env bash

FPSKWname="CACAO_FPSPROC_CMDMCOMB"

FPSKWval="NULL"
if [ ! -z "${CACAO_FPSPROC_CMDMCOMB+x}" ]; then
	FPSKWval="$CACAO_FPSPROC_CMDMCOMB"
fi


# FPS name
fpsname="DMcomb"
fpsarg0="cm${CACAO_DMINDEX}"

# FPS full name
fpsfname="${fpsname}-${fpsarg0}"

# function call
fpsfcall="cacaodm.DMcomb"

# short description
fpsdescr="Combine DM channels"




function fpsentry_addmodules() {
	echo "no module to be added"
}

function fpsentry_addcmds() {
	CACAO_CMDMINDEX=2
	addfpscmd "setval ${fpsfname}.procinfo.loopcntMax -1"
	addfpscmd "setval ${fpsfname}.procinfo.triggermode 4" # delay
	addfpscmd "setval ${fpsfname}.procinfo.triggerdelay 0.00001" # 10us
	addfpscmd "setval ${fpsfname}.DMindex ${CACAO_CMDMINDEX}"
	addfpscmd "setval ${fpsfname}.DMxsize 100"
	addfpscmd "setval ${fpsfname}.DMysize 1"
}




source milk-fpslist-addentry
