#!/usr/bin/env bash

MSdescr="Archive AO calibration"

MSextdescr="Copy current filesystem calibration to AOcalibs/<calibname>/ directory"

source milk-script-std-config


RequiredCommands=(milk)

RequiredFiles=(LOOPNUMBER)


if [ -f LOOPNUMBER ]; then
AOLOOPNUMBER=$( head -1 LOOPNUMBER )
else
echo "Error: no LOOPNUMBER file. Are we running this from the correct directory ?"
exit
fi

RequiredDirs=(AOcalibs fps.compfCM-${AOLOOPNUMBER}.datadir fps.acqlin_zRM-${AOLOOPNUMBER}.datadir fps.acqlin_loRM-${AOLOOPNUMBER}.datadir)

MSarg+=( "calibname:string:calibration name" )



MSopt+=( "u:update:setupdate::update existing, do not append timestamp" )

update="0"
function setupdate() {
        echo "Updating, not apppending timestamp"
        update="1"
}



source milk-argparse
set +u
if [ "${EXITSTATUS}" = "1" ]; then
exit
fi
set -u




calib="${inputMSargARRAY[0]}"

echo "Calibration : ${calib}"





# Arguments:
# Calib name


ARCHDIR="AOcalibs/$1"

if [ "${update}" = "0" ]; then
ARCHDIR=${ARCHDIR}_$(date -u +%Y%m%d_%H%M%S)
fi


mkdir -p ${ARCHDIR}


cp fps.compfCM-${AOLOOPNUMBER}.datadir/mkmodestmp/fmodesWFS1all.fits ${ARCHDIR}/aol${AOLOOPNUMBER}_modesWFS.fits
cp fps.compfCM-${AOLOOPNUMBER}.datadir/mkmodestmp/fmodes2ball.fits ${ARCHDIR}/aol${AOLOOPNUMBER}_DMmodes.fits

# modes including WFS-space diagonalization
cp fps.compfCM-${AOLOOPNUMBER}.datadir/mkmodestmp/fmodesWFSall.fits ${ARCHDIR}/aol${AOLOOPNUMBER}_modesWFS_WFSdiag.fits
cp fps.compfCM-${AOLOOPNUMBER}.datadir/mkmodestmp/fmodesall.fits ${ARCHDIR}/aol${AOLOOPNUMBER}_DMmodes_WFSdiag.fits

# copy the block structure files
cp fps.compfCM-${AOLOOPNUMBER}.datadir/param_NBmodeblocks.txt ${ARCHDIR}/aol${AOLOOPNUMBER}_NBmodeblocks.txt
cp fps.compfCM-${AOLOOPNUMBER}.datadir/param_NBmodes.txt ${ARCHDIR}/aol${AOLOOPNUMBER}_NBmodes.txt

# and copy the block files for future reference
for f in $(ls fps.compfCM-${AOLOOPNUMBER}.datadir/block*.txt) ; do
   cp $f ${ARCHDIR}/aol${AOLOOPNUMBER}_$(basename $f)
done



cp fps.acqlin_zRM-${AOLOOPNUMBER}.datadir/wfsref_mn.fits ${ARCHDIR}/aol${AOLOOPNUMBER}_wfsref.fits
cp fps.acqlin_zRM-${AOLOOPNUMBER}.datadir/wfsmask_mkm.fits ${ARCHDIR}/aol${AOLOOPNUMBER}_wfsmask.fits
cp fps.acqlin_zRM-${AOLOOPNUMBER}.datadir/wfsmap.fits ${ARCHDIR}/aol${AOLOOPNUMBER}_wfsmap.fits
cp fps.acqlin_zRM-${AOLOOPNUMBER}.datadir/dmmask_mkm.fits ${ARCHDIR}/aol${AOLOOPNUMBER}_dmmask.fits
cp fps.acqlin_zRM-${AOLOOPNUMBER}.datadir/dmslaved.fits ${ARCHDIR}/aol${AOLOOPNUMBER}_dmslaved.fits
cp fps.acqlin_zRM-${AOLOOPNUMBER}.datadir/zrespM.fits ${ARCHDIR}/aol${AOLOOPNUMBER}_zrespM.fits


cp fps.acqlin_loRM-${AOLOOPNUMBER}.datadir/respM.fits ${ARCHDIR}/aol${AOLOOPNUMBER}_LOrespM.fits
cp fps.acqlin_loRM-${AOLOOPNUMBER}.datadir/RMpokeCube.fits ${ARCHDIR}/aol${AOLOOPNUMBER}_LODMmodes.fits


# write out complete path so someone following a symlink can easily track where we are
echo $(pwd)/${ARCHDIR} > ${ARCHDIR}/aol${AOLOOPNUMBER}_calib_dir.txt

# append timestamp
echo $(date -u --iso-8601=seconds) >> ${ARCHDIR}/aol${AOLOOPNUMBER}_calib_archived.txt

echo "$(date -u --iso-8601=seconds) ARCHIVE ${calib}" >> AOcalibs/AOcalib-${AOLOOPNUMBER}-log.txt
