#!/usr/bin/env bash


MSdescr="AO modal stats TUI"

MSextdescr="Displays modal stats
"

source milk-script-std-config

# check and load cacaovars
source cacao-check-cacaovars
RequiredCommands=( cacao )
RequiredPipes=()
RequiredFiles=()
RequiredDirs=()



source milk-argparse

set +u
if [ "${EXITSTATUS}" = "1" ]; then
	exit 1
fi
set -u



ttystring=$( tty | tr -d \/ )
pname="modalstatsTUI"
fifoname="$MILK_SHM_DIR/milkCLIfifo.${pname}.${ttystring}"
SF="$MILK_SHM_DIR/milkCLIstartup.${pname}.${ttystring}"
echo "readshmim aol${CACAO_LOOPNUMBER}_DMmodes" > $SF
echo "readshmim aol${CACAO_LOOPNUMBER}_modevalWFS" >> $SF
echo "readshmim aol${CACAO_LOOPNUMBER}_modevalDM" >> $SF
echo "readshmim aol${CACAO_LOOPNUMBER}_modevalOL" >> $SF
echo "readshmim aol${CACAO_LOOPNUMBER}_mgain" >> $SF
echo "readshmim aol${CACAO_LOOPNUMBER}_mmult" >> $SF
echo "readshmim aol${CACAO_LOOPNUMBER}_mlimit" >> $SF
echo "readshmim aol${CACAO_LOOPNUMBER}_mlimitcntfrac" >> $SF
echo "readshmim aol${CACAO_LOOPNUMBER}_mvalWFSave" >> $SF
echo "readshmim aol${CACAO_LOOPNUMBER}_mvalWFSrms" >> $SF
echo "readshmim aol${CACAO_LOOPNUMBER}_mvalDMave" >> $SF
echo "readshmim aol${CACAO_LOOPNUMBER}_mvalDMrms" >> $SF
echo "readshmim aol${CACAO_LOOPNUMBER}_mvalOLave" >> $SF
echo "readshmim aol${CACAO_LOOPNUMBER}_mvalOLrms" >> $SF
echo "listim" >> $SF
echo "cacao.modalstatsTUI ${CACAO_LOOPNUMBER}" >> $SF
echo "exitCLI" >> $SF

MILK_QUIET=1 cacao -n ${pname} -f ${fifoname} -s $SF

