#!/usr/bin/env bash

MSdescr="list cacao- scripts"

MSextdescr="List cacao scripts

Scan system for cacao- commands

"

source milk-script-std-config

PRINTPATH="0"
MSopt+=( "p:path:set_printpath::Print command path" )
function set_printpath()
{
	PRINTPATH="1"
}

PRINTDATE="0"
MSopt+=( "d:date:set_printdate::Print command date" )
function set_printdate()
{
	PRINTDATE="1"
}

source milk-argparse


CMDLIST=$(compgen -c "cacao-" | sort -u )

GREEN='\033[0;32m'
NC='\033[0m' # No Color

echo "LIST OF CACAO COMMANDS :"

for cmd in $CMDLIST; do
	if [ "${PRINTPATH}" = "1" ]; then
		pathstring="$(which ${cmd})"
		printf "	${GREEN}%-32s${NC}  %s\n" "$cmd" "${pathstring}"
	elif [ "${PRINTDATE}" = "1" ]; then
		filename="$(which ${cmd})"
		datestring="$(date -r $filename '+%Y-%m-%dT%H:%M:%SZ')"
		CMDLISTOUT+="$(printf "%s  %s;" "${datestring}" "$cmd")"
	else
		helpline=$( $cmd -hs | head -n 1 )
		printf "	${GREEN}%-32s${NC}  %s\n" "$cmd" "$helpline"
	fi

done


if [ "${PRINTDATE}" = "1" ]; then
	IFS=';' read -r -a array <<< "${CMDLISTOUT//[$'\t\r\n']}"; unset IFS
	IFS=$'\n' sortedarray=($(sort <<<"${array[*]}")); unset IFS	
	for element in "${sortedarray[@]//[$'\t\r\n']}"
	do
		cmdstr=$(echo $element | awk '{ print $2}')
		datestr=$(echo $element | awk '{ print $1}')
		helpline=$( $cmdstr -hs | head -n 1 )
		printf " %s ${GREEN}%-32s${NC}  %s\n" "$datestr" "$cmdstr" "$helpline"
	done
fi
