#!/usr/bin/env bash

FPSKWname="CACAO_FPSPROC_ZONALFILTERING"

FPSKWval="NULL"
if [ ! -z "${CACAO_FPSPROC_ZONALFILTERING+x}" ]; then
	FPSKWval="$CACAO_FPSPROC_ZONALFILTERING"
fi


# FPS name
fpsname="zfilt"
fpsarg0="${CACAO_LOOPNUMBER}"

# FPS full name
fpsfname="${fpsname}-${fpsarg0}"

# function call
fpsfcall="cacao-fpsexec-cacao-zonalfilter"

# short description
fpsdescr="Zonal filtering"



function fpsentry_addmodules() {
	echo "no module to be added"
}

function fpsentry_addcmds() {
	addfpscmd "setval ${fpsfname}.procinfo.loopcntMax -1"
	addfpscmd "setval ${fpsfname}.procinfo.triggermode 3"
	addfpscmd "setval ${fpsfname}.procinfo.triggersname aol${CACAO_LOOPNUMBER}_zvalDM"

	addfpscmd "setval ${fpsfname}.inzval aol${CACAO_LOOPNUMBER}_zvalDM"
	addfpscmd "setval ${fpsfname}.outzval aol${CACAO_LOOPNUMBER}_zvalDMf"
}

source milk-fpslist-addentry
