#!/usr/bin/env bash

CACAOTASK_SCRIPT_FNAME=$0
source cacaotask-check # check environment

# ======================================================================
# PERFORM ACTIONS FOR THIS TASK
# ======================================================================
echo "CACAO_LOOPNAME    : ${CACAO_LOOPNAME}"
echo "CONFDIR           : ${CONFDIR}"



echo "CACAO_LOOPROOTDIR : ${CACAO_LOOPROOTDIR}"


mkdir -p ${CACAO_LOOPROOTDIR}

# check if successful
if [ "$?" = 0 ]; then
    cacaotask_RETURNCODE=${CACAOTASK_RUN_SUCCESS}
else
    cacaotask_RETURNCODE=${CACAOTASK_RUN_FAIL}
fi

# copy test configuration files to work directory
cp ${CONFDIR}/cacaovars.bash ${CACAO_LOOPROOTDIR}/cacaovars.${CACAO_LOOPNAME}.bash
cp ${CONFDIR}/cacao-fpslistadd-* ${CACAO_LOOPROOTDIR}/

cp ${CONFDIR}/fpssetup.setval.conf ${CACAO_LOOPROOTDIR}/fpssetup.setval.${CACAO_LOOPNAME}.conf

# copy all scripts

cp ${CONFDIR}/aorun-* ${CACAO_LOOPROOTDIR}/


# ======================================================================
# WRITE CLEANUP SCRIPT FOR THIS TASK
# ======================================================================

fpsCTRLtmuxname="${CACAO_LOOPNAME}_fpsCTRL"

# Inside cat <<EOT section :
# ${VAR} will be resolved prior to writing to destination
# \${VAR} will not be resolved, and will appear as ${VAR} in the destination
#
cat <<EOT >>  ${CLEANSCRIPT}

rm ${CACAO_LOOPROOTDIR}/cacaovars.${CACAO_LOOPNAME}.bash
rm ${CACAO_LOOPROOTDIR}/fpssetup.setval.${CACAO_LOOPNAME}.conf
rm ${CACAO_LOOPROOTDIR}/aorun-*

echo "Waiting for tmux session ${fpsCTRLtmuxname} to termninate"

until [[ ! "\$(tmux ls)" == *"${fpsCTRLtmuxname}"* ]]
do
	sleep 0.2
  echo -n "."
done
echo ""


while true; do
    read -p "REMOVING directory ./\${CACAO_LOOPROOTDIR} ? [y/n] " yn
    case \$yn in
        [Yy]* ) rm -r ./\${CACAO_LOOPROOTDIR}; break;;
        [Nn]* ) echo "not removing directory"; break;;
        * ) echo "Please answer yes or no.";;
    esac
done


EOT


# ======================================================================
# STORE OUTPUT ENVIRONMENT VARIABLES
# ======================================================================

# NEWVAR_INITSETUP=2
# echo "NEWVAR_INITSETUP=${NEWVAR_INITSETUP}" >> ${ENVOUTFILE}
