#!/usr/bin/env bash

MILKCLI_APPNAME="cacao-cli" MILKCLI_ADD_LIBS="$MILKCLI_ADD_LIBS;cacaoAOloopControl,cacaoAOloopControlIOtools,cacaoAOloopControlcompTools,cacaoAOloopControlacquireCalib,cacaocomputeCalib,cacaoAOloopControlDM,cacaoAOloopControlperfTest,cacaoAOloopControlPredictiveControl" milk-cli "$@"
