#!/usr/bin/env bash

# Arguments:
# Calib name



ARCHDIR="AOcalibs/$1"

if [[ -d "${ARCHDIR}" ]]; then

milk <<EOF
loadfits "${ARCHDIR}/aol0_modesWFS.fits" aol0mWFS
cpsh aol0mWFS aol0_modesWFS

loadfits "${ARCHDIR}/aol0_DMmodes.fits" aol0mDM
cpsh aol0mDM  aol0_DMmodes

loadfits "${ARCHDIR}/aol0_wfsref.fits" aol0wfsref
cpsh aol0wfsref aol0_wfsref

loadfits "${ARCHDIR}/aol0_wfsmask.fits" aol0wfsmask
cpsh aol0wfsmask aol0_wfsmask


loadfits "${ARCHDIR}/aol0_wfsmap.fits" aol0wfsmap
cpsh aol0wfsmap aol0_wfsmap

loadfits "${ARCHDIR}/aol0_dmmask.fits" aol0dmmask
cpsh aol0dmmask aol0_dmmask

loadfits "${ARCHDIR}/aol0_dmslaved.fits" aol0dmslaved
cpsh aol0dmslaved aol0_dmslaved

loadfits "${ARCHDIR}/aol0_zrespM.fits" aol0zrespM
cpsh aol0zrespM aol0_zrespM

loadfits "${ARCHDIR}/aol0_LOrespM.fits" aol0LOrespM
cpsh aol0LOrespM aol0_LOrespM

loadfits "${ARCHDIR}/aol0_LODMmodes.fits" aol0LODMmodes
cpsh aol0LODMmodes aol0_LODMmodes

exitCLI
EOF

else
    echo "DIRECTORY DOES NOT EXIST"
fi
