#!/usr/bin/env bash

# This script uses milk-argparse
# See template milk-scriptexample in module milk_module_example for template and instructions

# script 1-line description
MSdescr="cacao fpsCTRL log"

MSextdescr="ASCII log displayed in ncurrent terminal
log is tee-ed to logdir
CTRL+C to stop

This script should be restated at each start of observation
"

source milk-script-std-config
source cacao-check-cacaovars



LogRebuild=0
MSopt+=( "r:rebuild:set_rebuild::rebuild log from start of UT day" )
function set_rebuild() {
	LogRebuild=1
}

source milk-argparse



# logdir can be symlink (usually to current day log folder)
datestr="$(date -u +'%Y%m%d')"

# default log directory is upstream of ROOTDIR so it persists
#
LOGDIR="../logdir-${CACAO_LOOPNAME}/${datestr}"
mkdir -p ${LOGDIR}

LOGFILEEXT="${LOGDIR}/fpsctrl.${CACAO_LOOPNAME}.log"


if [ ${LogRebuild} = 1 ]; then

	# flush output file
	if [ -f ${LOGFILEEXT} ]; then
		rm ${LOGFILEEXT}
	fi

	# unix time at start of day (UTC)
	# we only copy to current day
	#
	utimedaystart=$(date -d "$(date -u +'%Y-%m-%d UTC')" +"%s")

	# write previous entries
	awk '{if ($2>'$utimedaystart') print $0}' fpsCTRL.log | grep -v "DEBUG" >> ${LOGFILEEXT}
fi



tail -n 100 fpsCTRL.log  | grep --line-buffered -v "DEBUG" | sed \
    -e 's/\(CMDOK\)/\x1B[32m\1\x1B[0m/' \
    -e 's/\(ALIVE\)/\x1B[1;92m\1\x1B[0m/' \
    -e 's/\(STOPPED\)/\x1B[1;93m\1\x1B[0m/' \
    -e 's/\(CRASHED\)/\x1B[0;101m\1\x1B[0m/' \
    -e 's/\(ONOFF ON\)/\x1B[1;92m\1\x1B[0m/' \
    -e 's/\(ONOFF OFF\)/\x1B[1;93m\1\x1B[0m/' \
    -e 's/\(ERROR\)/\x1B[0;101m\1\x1B[0m/' \
    -e 's/\(CMDFAIL\)/\x1B[0;101m\1\x1B[0m/' \
    -e 's/\(FPSCTRL\)/\x1B[1\;33m\1\x1B[0m/' \
    -e 's/\(SETVAL\)/\x1B[1;96m\1\x1B[0m/'

if [ ${LogRebuild} = 1 ]; then
	nbloglines=$(wc -l ${LOGFILEEXT})
	echo ""
	echo ">>>>>>>>>>> LOGGED ${nbloglines} LINES AHEAD OF THIS POINT <<<<<<<<<<<"
	echo ""
else
	echo ""
	echo ">>>>>>>>>>> START LOGGING FROM THIS POINT <<<<<<<<<<<"
	echo ""
fi

tail -f -n0 fpsCTRL.log  | grep --line-buffered -v "DEBUG" | tee -a ${LOGFILEEXT} | sed \
    -e 's/\(CMDOK\)/\x1B[32m\1\x1B[0m/' \
    -e 's/\(ALIVE\)/\x1B[1;92m\1\x1B[0m/' \
    -e 's/\(STOPPED\)/\x1B[1;93m\1\x1B[0m/' \
    -e 's/\(CRASHED\)/\x1B[0;101m\1\x1B[0m/' \
    -e 's/\(ONOFF ON\)/\x1B[1;92m\1\x1B[0m/' \
    -e 's/\(ONOFF OFF\)/\x1B[1;93m\1\x1B[0m/' \
    -e 's/\(ERROR\)/\x1B[0;101m\1\x1B[0m/' \
    -e 's/\(CMDFAIL\)/\x1B[0;101m\1\x1B[0m/' \
    -e 's/\(FPSCTRL\)/\x1B[1\;33m\1\x1B[0m/' \
    -e 's/\(SETVAL\)/\x1B[1;96m\1\x1B[0m/'




exit

# Reset
Color_Off='\033[0m'       # Text Reset

# Regular Colors
Black='\033[0;30m'        # Black
Red='\033[0;31m'          # Red
Green='\033[0;32m'        # Green
Yellow='\033[0;33m'       # Yellow
Blue='\033[0;34m'         # Blue
Purple='\033[0;35m'       # Purple
Cyan='\033[0;36m'         # Cyan
White='\033[0;37m'        # White

# Bold
BBlack='\033[1;30m'       # Black
BRed='\033[1;31m'         # Red
BGreen='\033[1;32m'       # Green
BYellow='\033[1;33m'      # Yellow
BBlue='\033[1;34m'        # Blue
BPurple='\033[1;35m'      # Purple
BCyan='\033[1;36m'        # Cyan
BWhite='\033[1;37m'       # White

# Underline
UBlack='\033[4;30m'       # Black
URed='\033[4;31m'         # Red
UGreen='\033[4;32m'       # Green
UYellow='\033[4;33m'      # Yellow
UBlue='\033[4;34m'        # Blue
UPurple='\033[4;35m'      # Purple
UCyan='\033[4;36m'        # Cyan
UWhite='\033[4;37m'       # White

# Background
On_Black='\033[40m'       # Black
On_Red='\033[41m'         # Red
On_Green='\033[42m'       # Green
On_Yellow='\033[43m'      # Yellow
On_Blue='\033[44m'        # Blue
On_Purple='\033[45m'      # Purple
On_Cyan='\033[46m'        # Cyan
On_White='\033[47m'       # White

# High Intensity
IBlack='\033[0;90m'       # Black
IRed='\033[0;91m'         # Red
IGreen='\033[0;92m'       # Green
IYellow='\033[0;93m'      # Yellow
IBlue='\033[0;94m'        # Blue
IPurple='\033[0;95m'      # Purple
ICyan='\033[0;96m'        # Cyan
IWhite='\033[0;97m'       # White

# Bold High Intensity
BIBlack='\033[1;90m'      # Black
BIRed='\033[1;91m'        # Red
BIGreen='\033[1;92m'      # Green
BIYellow='\033[1;93m'     # Yellow
BIBlue='\033[1;94m'       # Blue
BIPurple='\033[1;95m'     # Purple
BICyan='\033[1;96m'       # Cyan
BIWhite='\033[1;97m'      # White

# High Intensity backgrounds
On_IBlack='\033[0;100m'   # Black
On_IRed='\033[0;101m'     # Red
On_IGreen='\033[0;102m'   # Green
On_IYellow='\033[0;103m'  # Yellow
On_IBlue='\033[0;104m'    # Blue
On_IPurple='\033[0;105m'  # Purple
On_ICyan='\033[0;106m'    # Cyan
On_IWhite='\033[0;107m'   # White
