#!/usr/bin/env bash

FPSKWname="CACAO_FPSPROC_MFILTTEST"

FPSKWval="NULL"
if [ ! -z "${CACAO_FPSPROC_MFILTTEST+x}" ]; then
	FPSKWval="$CACAO_FPSPROC_MFILTTEST"
fi


# FPS name
fpsname="mfiltt"
fpsarg0="${CACAO_LOOPNUMBER}"

# FPS full name
fpsfname="${fpsname}-${fpsarg0}"

# function call
fpsfcall="cacao-cli.mfilttest"

# short description
fpsdescr="Modal filtering test input"



function fpsentry_addmodules() {
	echo "no module to be added"
}

function fpsentry_addcmds() {
	addfpscmd "setval ${fpsfname}.AOloopindex ${CACAO_LOOPNUMBER}"
	addfpscmd "setval ${fpsfname}.procinfo.loopcntMax -1"
	addfpscmd "setval ${fpsfname}.procinfo.triggermode 4"
	addfpscmd "setval ${fpsfname}.procinfo.triggerdelay 0.01"
	
	addfpscmd "setval ${fpsfname}.mvalDM aol${CACAO_LOOPNUMBER}_mfiltt_mvalDM"
	addfpscmd "setval ${fpsfname}.mvalWFS aol${CACAO_LOOPNUMBER}_mfiltt_mvalWFS"
}



source milk-fpslist-addentry
