#!/usr/bin/env bash

# This script uses milk-argparse
# See template milk-scriptexample in module milk_module_example for template and instructions

# script 1-line description
MSdescr="AO loop execution script"



source cacaovars.*.bash

# Extended description
MSextdescr="AO loop script

CACAO_LOOPNAME = ${CACAO_LOOPNAME}
"


# standard configuration
# location ./scripts/
source milk-script-std-config

# prerequisites
#

RequiredCommands=( tmux milk )

fpsCTRLtmuxname="${CACAO_LOOPNAME}_fpsCTRL"
fpsCTRLfifo="${MILK_SHM_DIR}/${fpsCTRLtmuxname}.fifo"
RequiredPipes=( ${fpsCTRLfifo} )

RequiredDirs=()





# SCRIPT MANDATORY ARGUMENTS
# syntax: "name:type(s)/test(s):description"
#



# SCRIPT OPTIONS
# syntax: "short:long:functioncall:args[types]:description"
#

# parse arguments
source milk-argparse




function sendFPScmd {
    echo "SENDING: $1"
    echo "$1" >> ${fpsCTRLfifo}
}




# ======================================================================
# Starting DM combination process
# ======================================================================

sendFPScmd "setval DMch2disp-${CACAO_DMINDEX}.option.DClevel 0.0"
#taskset_DMch2disp="3"
#sendFPScmd "setval DMch2disp-${CACAO_DMINDEX}.procinfo.taskset ${taskset_DMch2disp}"
sendFPScmd "confwupdate DMch2disp-${CACAO_DMINDEX}"
sendFPScmd "runstart DMch2disp-${CACAO_DMINDEX}"

# ======================================================================
# Starting DM hardware delay simulator
# ======================================================================

sendFPScmd "confwupdate streamDelay-${CACAO_DMINDEX}"
sendFPScmd "runstart streamDelay-${CACAO_DMINDEX}"


# ======================================================================
# Starting MVM simulator
# ======================================================================
sendFPScmd "setval simmvmgpu-${CACAO_LOOPNUMBER}.procinfo.triggerdelay 0.01"
sendFPScmd "confwupdate simmvmgpu-${CACAO_LOOPNUMBER}"
sendFPScmd "runstart simmvmgpu-${CACAO_LOOPNUMBER}"


# WAIT for aolX_linsimWFS to appear
filename="${MILK_SHM_DIR}/aol${CACAO_LOOPNUMBER}_linsimWFS.im.shm"
echo "Waiting for file ${filename} ..."
until [ -f "$filename" ]
do
     sleep 0.1
done

# ======================================================================
# Liniking
# ======================================================================

rm ${MILK_SHM_DIR}/aol${CACAO_LOOPNUMBER}_wfsim.im.shm
ln -s ${MILK_SHM_DIR}/aol${CACAO_LOOPNUMBER}_linsimWFS.im.shm ${MILK_SHM_DIR}/aol${CACAO_LOOPNUMBER}_wfsim.im.shm
