#!/usr/bin/env bash

FPSKWname="CACAO_FPSPROC_SPOTPOS"

FPSKWval="NULL"
if [ ! -z "${CACAO_FPSPROC_SPOTPOS+x}" ]; then
	FPSKWval="$CACAO_FPSPROC_SPOTPOS"
fi


# FPS name
fpsname="spotpos"
fpsarg0="${CACAO_LOOPNUMBER}"

# FPS full name
fpsfname="${fpsname}-${fpsarg0}"

# function call
fpsfcall="cacaoio.spotpos"

# short description
fpsdescr="Measure spot position"



function fpsentry_addmodules() {
	echo "no module to be added"
}

function fpsentry_addcmds() {
    addfpscmd "setval ${fpsfname}.insname aol${CACAO_LOOPNUMBER}_wfsim"

    addfpscmd "setval ${fpsfname}.procinfo.loopcntMax -1" # infinite loop
    addfpscmd "setval ${fpsfname}.procinfo.triggermode 3" # semaphore
    addfpscmd "setval ${fpsfname}.procinfo.triggersname aol${CACAO_LOOPNUMBER}_wfsim"

    addfpscmd "setval ${fpsfname}.outspotpos aol${CACAO_LOOPNUMBER}_ttpos"
}



source milk-fpslist-addentry
