#!/usr/bin/env bash

# This script uses milk-argparse
# See template milk-scriptexample in module milk_module_example for template and instructions

# script 1-line description
MSdescr="AO loop execution script"
# Extended description
MSextdescr="AO loop script"
source milk-script-std-config
source cacao-check-cacaovars

MSarg+=( "action:string:action (start/stop/check)" )
source milk-argparse
ACTION="${inputMSargARRAY[0]}"


ACTIONOK=0



if [ ${ACTION} == "check" ]; then
ACTIONOK=1
fi

# Checking FPS
FPScheckOK="OK"
checkFPSON CACAO_FPSPROC_DMCH2DISPSIM ${CACAO_FPSPROC_DMCH2DISPSIM}
echo "FPScheckOK = ${FPScheckOK}"

if [ ${FPScheckOK} == "FAIL" ]; then
echo "[$(tput setaf 1)$(tput bold) FAILED $(tput sgr0)] FPS check failed"
exit
fi




if [ ${ACTION} == "start" ]; then
ACTIONOK=1
# ======================================================================
# Starting DM combination process
# ======================================================================

sendFPScmd "setval DMch2disp-${CACAO_DMINDEXSIM}.option.voltmode OFF"
sendFPScmd "setval DMch2disp-${CACAO_DMINDEXSIM}.option.DClevel 0.0"
#taskset_DMch2disp="3"
#sendFPScmd "setval DMch2disp-${CACAO_DMINDEXSIM}.procinfo.taskset ${taskset_DMch2disp}"
sendFPScmd "confwupdate DMch2disp-${CACAO_DMINDEXSIM}"
sendFPScmd "runstart DMch2disp-${CACAO_DMINDEXSIM}"

# WAIT for dm${CACAO_DMINDEXSIM}disp to appear
filename="${MILK_SHM_DIR}/dm${CACAO_DMINDEXSIM}disp.im.shm"
echo "Waiting for file ${filename} ..."
until [ -f "$filename" ]
do
     sleep 0.1
done
milk-shmim-zero aol${CACAO_LOOPNUMBER}_dmC

fi


if [ ${ACTION} == "stop" ]; then
ACTIONOK=1
sendFPScmd "runstop DMch2disp-${CACAO_DMINDEXSIM}"
fi




if [ ${ACTIONOK} == 0 ]; then
echo "[$(tput setaf 1)$(tput bold) FAILED $(tput sgr0)] ACTION $ACTION undefined"
fi
