#!/usr/bin/env bash

# This script uses milk-argparse
# See template milk-scriptexample in module milk_module_example for template and instructions

# script 1-line description
MSdescr="Take reference (from imWFS2)"
# Extended description
MSextdescr="Acquire WFS reference by averaging imWFS2"
source milk-script-std-config
source cacao-check-cacaovars



NBframe="1000"
MSopt+=( "n:nbframe:set_NBframe:nbframe[long]:set number of frames" )
function set_NBframe() {
	NBframe="$1"
}

source milk-argparse


# Checking stream
streamcheckOK="OK"
checkstream aol${CACAO_LOOPNUMBER}_imWFS2

if [ ${streamcheckOK} == "FAIL" ]; then
	echo "[$(tput setaf 1)$(tput bold) FAILED $(tput sgr0)] stream check failed"
	cacaomsglog "ERROR streamcheck"
	exit 1
fi

cacaomsglog "NBframe ${NBframe}"

#MILK_QUIET=1 
milk << EOF
readshmim aol${CACAO_LOOPNUMBER}_imWFS1
streamave ..procinfo 1
streamave ..triggersname aol${CACAO_LOOPNUMBER}_imWFS1
streamave ..triggermode 3
streamave ..loopcntMax ${NBframe}
streamave aol${CACAO_LOOPNUMBER}_imWFS1 wfsref ${NBframe}
saveFITS wfsref "aol${CACAO_LOOPNUMBER}_wfsref.fits"
cpsh wfsref aol${CACAO_LOOPNUMBER}_wfsref
cpsh wfsref aol${CACAO_LOOPNUMBER}_wfsrefc
listim
exitCLI
EOF

cacaomsglog "END"
