#!/usr/bin/env bash

# This script uses milk-argparse
# See template milk-scriptexample in module milk_module_example for template and instructions

# script 1-line description
MSdescr="AO loop execution script"

MSextdescr="AO loop script"
source milk-script-std-config
source cacao-check-cacaovars
source milk-argparse




errexit=0

# Checking FPS
FPScheckOK="OK"
checkFPSON CACAO_FPSPROC_COMPSTRCM ${CACAO_FPSPROC_COMPSTRCM}

if [ ${FPScheckOK} == "FAIL" ]; then
echo "[$(tput setaf 1)$(tput bold) FAILED $(tput sgr0)] FPS check failed"
errexit=1
fi


if [ $errexit = 1 ]; then
exit
fi




# ======================================================================
# Compute straight CM
# ======================================================================

# set ouput files
mkdir -p conf/CMmodesDM/
mkdir -p conf/CMmodesWFS/
sendFPScmd "setval compstrCM-${CACAO_LOOPNUMBER}.CMmodesDM ../conf/CMmodesDM/CMmodesDM.fits"
sendFPScmd "setval compstrCM-${CACAO_LOOPNUMBER}.CMmodesWFS ../conf/CMmodesWFS/CMmodesWFS.fits"


sendFPScmd "confwupdate compstrCM-${CACAO_LOOPNUMBER}"
sendFPScmd "runstart compstrCM-${CACAO_LOOPNUMBER}"


# Load CM to shared memory

milk-FITS2shm "conf/CMmodesWFS/CMmodesWFS.fits" aol${CACAO_LOOPNUMBER}_modesWFS
milk-FITS2shm "conf/CMmodesDM/CMmodesDM.fits" aol${CACAO_LOOPNUMBER}_DMmodes
