#!/usr/bin/env bash

# This script uses milk-argparse
# See template milk-scriptexample in module milk_module_example for template and instructions

# script 1-line description
MSdescr="Acquire WFS data"


MSextdescr="reads from aolX_wfsim
Subtract dark      -> aolX_imWFS0
Normalizes flux    -> aolX_imWFS1
Subtract reference -> aolX_imWFS2"
source milk-script-std-config
source cacao-check-cacaovars

MSarg+=( "action:string:action (start/check)" )


WaitForCompletion=0
MSopt+=( "w:waitfcomp:set_WaitForCompletion::wait for process to complete to exist script" )
function set_WaitForCompletion() {
	WaitForCompletion=1
}



source milk-argparse
ACTION="${inputMSargARRAY[0]}"


ACTIONOK=0




if [ ${ACTION} == "check" ]; then
ACTIONOK=1
fi

errexit=0

# Checking FPS
FPScheckOK="OK"
checkFPSON CACAO_FPSPROC_ACQUWFS ${CACAO_FPSPROC_ACQUWFS}

if [ ${FPScheckOK} == "FAIL" ]; then
echo "[$(tput setaf 1)$(tput bold) FAILED $(tput sgr0)] FPS check failed"
errexit=1
fi


# Checking stream
streamcheckOK="OK"
checkstream aol${CACAO_LOOPNUMBER}_wfsim

if [ ${streamcheckOK} == "FAIL" ]; then
echo "[$(tput setaf 1)$(tput bold) FAILED $(tput sgr0)] stream check failed"
errexit=1
fi


if [ $errexit = 1 ]; then
exit
fi









if [ ${ACTION} == "start" ]; then
ACTIONOK=1

if [ "$CACAO_WFSSTREAM_PROCESSED" = "ON" ]; then
echo "Processed WFS stream -> no scaling"
sendFPScmd "setval acquWFS-${CACAO_LOOPNUMBER}.comp.WFSnormalize OFF"
sendFPScmd "setval acquWFS-${CACAO_LOOPNUMBER}.comp.WFSrefsub OFF"
sendFPScmd "setval acquWFS-${CACAO_LOOPNUMBER}.comp.WFSsigav ON"
sendFPScmd "setval acquWFS-${CACAO_LOOPNUMBER}.comp.WFSrefc ON"
else
sendFPScmd "setval acquWFS-${CACAO_LOOPNUMBER}.comp.WFSnormalize ON"
sendFPScmd "setval acquWFS-${CACAO_LOOPNUMBER}.comp.WFSrefsub ON"
sendFPScmd "setval acquWFS-${CACAO_LOOPNUMBER}.comp.WFSsigav ON"
sendFPScmd "setval acquWFS-${CACAO_LOOPNUMBER}.comp.WFSrefc ON"
fi

sendFPScmd "confwupdate acquWFS-${CACAO_LOOPNUMBER}"
sendFPScmd "runstart acquWFS-${CACAO_LOOPNUMBER}"


if [ $WaitForCompletion == "1" ]; then
sname="aol${CACAO_LOOPNUMBER}_imWFS2"
echo "Waiting for stream ${sname}"
until [ -f "${MILK_SHM_DIR}/${sname}.im.shm" ]
do
     sleep 0.1
done
fi

fi





if [ ${ACTION} == "stop" ]; then
ACTIONOK=1

sendFPScmd "runstop acquWFS-${CACAO_LOOPNUMBER}"

fi




if [ ${ACTIONOK} == 0 ]; then
echo "[$(tput setaf 1)$(tput bold) FAILED $(tput sgr0)] ACTION $ACTION undefined"
fi
