#!/usr/bin/env bash

# This script uses milk-argparse
# See template milk-scriptexample in module milk_module_example for template and instructions

# script 1-line description
MSdescr="AO loop execution script"


MSextdescr="AO loop script"
source milk-script-std-config
source cacao-check-cacaovars


WaitForCompletion=0
MSopt+=( "w:waitfcomp:set_WaitForCompletion::wait for process to complete to exist script" )
function set_WaitForCompletion() {
	WaitForCompletion=1
}


source milk-argparse





errexit=0

# Checking FPS
FPScheckOK="OK"
checkFPSON CACAO_FPSPROC_MLAT ${CACAO_FPSPROC_MLAT}

if [ ${FPScheckOK} == "FAIL" ]; then
echo "[$(tput setaf 1)$(tput bold) FAILED $(tput sgr0)] FPS check failed"
errexit=1
fi


# Checking stream
streamcheckOK="OK"
checkstream aol${CACAO_LOOPNUMBER}_wfsim

if [ ${streamcheckOK} == "FAIL" ]; then
echo "[$(tput setaf 1)$(tput bold) FAILED $(tput sgr0)] stream check failed"
errexit=1
fi


if [ $errexit = 1 ]; then
exit
fi







# ======================================================================
# mlat
# ======================================================================

sendFPScmd "confwupdate mlat-${CACAO_LOOPNUMBER}"
sendFPScmd "runstart mlat-${CACAO_LOOPNUMBER}"

if [ $WaitForCompletion == "1" ]; then
echo "Waiting for completion ..."
pOK=1
while [ $pOK -gt 0 ]; do
	sleep 0.1
	pOK=$(ps -alx| grep mlat-${CACAO_LOOPNUMBER} | grep RUNSTART | wc -l)
done
fi
