#!/usr/bin/env bash

# This script uses milk-argparse
# See template milk-scriptexample in module milk_module_example for template and instructions

# script 1-line description
MSdescr="AO loop execution script"


MSextdescr="AO loop script"
source milk-script-std-config
source cacao-check-cacaovars

MSarg+=( "action:string:action (start/check)" )

source milk-argparse
ACTION="${inputMSargARRAY[0]}"


ACTIONOK=0




if [ ${ACTION} == "check" ]; then
ACTIONOK=1
fi

errexit=0

# Checking FPS
FPScheckOK="OK"
checkFPSON CACAO_FPSPROC_ACQUWFS ${CACAO_FPSPROC_ACQUWFS}

if [ ${FPScheckOK} == "FAIL" ]; then
echo "[$(tput setaf 1)$(tput bold) FAILED $(tput sgr0)] FPS check failed"
errexit=1
fi


# Checking stream
streamcheckOK="OK"
checkstream aol${CACAO_LOOPNUMBER}_wfsim

if [ ${streamcheckOK} == "FAIL" ]; then
echo "[$(tput setaf 1)$(tput bold) FAILED $(tput sgr0)] stream check failed"
errexit=1
fi


if [ $errexit = 1 ]; then
exit
fi









if [ ${ACTION} == "start" ]; then
ACTIONOK=1

sendFPScmd "setval acquWFS-${CACAO_LOOPNUMBER}.comp.WFSnormalize ON"
sendFPScmd "setval acquWFS-${CACAO_LOOPNUMBER}.comp.WFSrefsub ON"
sendFPScmd "setval acquWFS-${CACAO_LOOPNUMBER}.comp.WFSsigav ON"
sendFPScmd "setval acquWFS-${CACAO_LOOPNUMBER}.comp.WFSrefc ON"
sendFPScmd "setval acquWFS-${CACAO_LOOPNUMBER}.comp.imtotal ON"

sendFPScmd "confwupdate acquWFS-${CACAO_LOOPNUMBER}"
sendFPScmd "runstart acquWFS-${CACAO_LOOPNUMBER}"

fi





if [ ${ACTION} == "stop" ]; then
ACTIONOK=1

sendFPScmd "runstop acquWFS-${CACAO_LOOPNUMBER}"

fi




if [ ${ACTIONOK} == 0 ]; then
echo "[$(tput setaf 1)$(tput bold) FAILED $(tput sgr0)] ACTION $ACTION undefined"
fi
