#!/usr/bin/env bash

# This script uses milk-argparse
# See template milk-scriptexample in module milk_module_example for template and instructions

# script 1-line description
MSdescr="Inject turbulence on DM"

MSextdescr="Inject turbulence on DM channel 10"
source milk-script-std-config
source cacao-check-cacaovars


MSarg+=( "action:string:action (start/stop/check)" )
source milk-argparse
ACTION="${inputMSargARRAY[0]}"


ACTIONOK=0

if [ ${ACTION} == "check" ]; then
ACTIONOK=1
fi

# Checking FPS
FPScheckOK="OK"
checkFPSON CACAO_FPSPROC_DMATMTURB ${CACAO_FPSPROC_DMATMTURB}

if [ ${FPScheckOK} == "FAIL" ]; then
echo "[$(tput setaf 1)$(tput bold) FAILED $(tput sgr0)] FPS check failed"
exit
fi


TURBFILE="conf/turbseed0.fits"

if [ -f ${TURBFILE} ]; then
echo "Found file ${TURBFILE}"
else
echo "Creating file ${TURBFILE}"
sendFPScmd "setval DMatmturb-${CACAO_DMINDEX}.comp ON"
echo "Waiting for file ${TURBFILE}"
until [ -f ${TURBFILE} ]
do
     sleep 0.1
done
fi

if [ ${ACTION} == "start" ]; then
ACTIONOK=1
sendFPScmd "setval DMatmturb-${CACAO_DMINDEX}.dmstream aol${CACAO_LOOPNUMBER}_dmturb"
sendFPScmd "confwupdate DMatmturb-${CACAO_DMINDEX}"
sendFPScmd "runstart DMatmturb-${CACAO_DMINDEX}"
fi


if [ ${ACTION} == "stop" ]; then
ACTIONOK=1
sendFPScmd "runstop DMatmturb-${CACAO_DMINDEX}"
fi




if [ ${ACTIONOK} == 0 ]; then
echo "[$(tput setaf 1)$(tput bold) FAILED $(tput sgr0)] ACTION $ACTION undefined"
fi
