#!/usr/bin/env bash

# This script uses milk-argparse
# See template milk-scriptexample in module milk_module_example for template and instructions

# script 1-line description
MSdescr="WFS to mode values"

MSextdescr="WFS to mode values
"

source milk-script-std-config
source cacao-check-cacaovars


MSarg+=( "action:string:action (start/stop/check)" )
source milk-argparse
ACTION="${inputMSargARRAY[0]}"


ACTIONOK=0

if [ ${ACTION} == "check" ]; then
	ACTIONOK=1
fi


# Checking FPS
FPScheckOK="OK"
checkFPSON CACAO_FPSPROC_MVMGPU_WFS2CMODEVAL ${CACAO_FPSPROC_MVMGPU_WFS2CMODEVAL}

if [ ${FPScheckOK} == "FAIL" ]; then
	echo "[$(tput setaf 1)$(tput bold) FAILED $(tput sgr0)] FPS check failed"
	cacaomsglog "ERROR failed FPS check"
	exit 1
fi


if [ ${ACTION} == "start" ]; then
	ACTIONOK=1

	cacaomsglog "START"
	sendFPScmd "confwupdate wfs2cmodeval-${CACAO_LOOPNUMBER}"
	sendFPScmd "runstart wfs2cmodeval-${CACAO_LOOPNUMBER}"
fi



if [ ${ACTION} == "stop" ]; then
	ACTIONOK=1
	cacaomsglog "STOP"
	sendFPScmd "runstop wfs2cmodeval-${CACAO_LOOPNUMBER}"
fi



if [ ${ACTIONOK} == 0 ]; then
	cacaomsglog "ERROR undefined action"
	echo "[$(tput setaf 1)$(tput bold) FAILED $(tput sgr0)] ACTION $ACTION undefined"
	exit 1
fi

cacaomsglog "END"
