#!/usr/bin/env bash

# This script uses milk-argparse
# See template milk-scriptexample in module milk_module_example for template and instructions

# script 1-line description
MSdescr="Compute control matrix"

MSextdescr="Compute control matrix by SVD

Reads input from fps
Write output to ../conf/CMmodesDM/CMmodesDM.fits and ../conf/CMmodesWFS/CMmodesWFS.fits
Loads output control matrix (CM) into streams aolX_modesWFS and aolX_DMmodes
"
source milk-script-std-config
source cacao-check-cacaovars
source milk-argparse

cacaomsglog "START"


errexit=0

# Checking FPS
FPScheckOK="OK"
checkFPSON CACAO_FPSPROC_COMPSTRCM ${CACAO_FPSPROC_COMPSTRCM}

if [ ${FPScheckOK} == "FAIL" ]; then
echo "[$(tput setaf 1)$(tput bold) FAILED $(tput sgr0)] FPS check failed"
errexit=1
fi


if [ $errexit = 1 ]; then
exit
fi




# ======================================================================
# Compute straight CM
# ======================================================================

# set ouput files
mkdir -p conf/CMmodesDM/
mkdir -p conf/CMmodesWFS/
sendFPScmd "setval compstrCM-${CACAO_LOOPNUMBER}.CMmodesDM ../conf/CMmodesDM/CMmodesDM.fits"
sendFPScmd "setval compstrCM-${CACAO_LOOPNUMBER}.CMmodesWFS ../conf/CMmodesWFS/CMmodesWFS.fits"
sendFPScmd "setval compstrCM-${CACAO_LOOPNUMBER}.dmmask ../conf/dmmask.fits"
sendFPScmd "setval compstrCM-${CACAO_LOOPNUMBER}.wfsmask ../conf/wfsmask.fits"

# erase output
rm -f conf/CMmodesWFS/CMmodesWFS.fits
rm -f conf/CMmodesDM/CMmodesDM.fits

sendFPScmd "confwupdate compstrCM-${CACAO_LOOPNUMBER}"
sendFPScmd "runstart compstrCM-${CACAO_LOOPNUMBER}"


# Load CM to shared memory

echo "Waiting for file conf/CMmodesWFS/CMmodesWFS.fits"
until [ -f "conf/CMmodesWFS/CMmodesWFS.fits" ]
do
     sleep 0.1
done
milk-FITS2shm "conf/CMmodesWFS/CMmodesWFS.fits" aol${CACAO_LOOPNUMBER}_modesWFS


echo "Waiting for file conf/CMmodesDM/CMmodesDM.fits"
until [ -f "conf/CMmodesDM/CMmodesDM.fits" ]
do
     sleep 0.1
done
milk-FITS2shm "conf/CMmodesDM/CMmodesDM.fits" aol${CACAO_LOOPNUMBER}_DMmodes

cacaomsglog "END"
