#!/usr/bin/env bash

# This script uses milk-argparse
# See template milk-scriptexample in module milk_module_example for template and instructions

# script 1-line description
MSdescr="Modal filtering and control"

MSextdescr="Modal filtering and control
"

source milk-script-std-config
source cacao-check-cacaovars


MSarg+=( "action:string:action (start/stop/check)" )
source milk-argparse
ACTION="${inputMSargARRAY[0]}"


ACTIONOK=0

if [ ${ACTION} == "check" ]; then
	ACTIONOK=1
fi

# Checking FPS
FPScheckOK="OK"
checkFPSON CACAO_FPSPROC_MODALFILTERING ${CACAO_FPSPROC_MODALFILTERING}

if [ ${FPScheckOK} == "FAIL" ]; then
	echo "[$(tput setaf 1)$(tput bold) FAILED $(tput sgr0)] FPS check failed"
	cacaomsglog "ERROR FPScheck"
	exit 1
fi




if [ ${ACTION} == "start" ]; then
	ACTIONOK=1
	cacaomsglog "START"
	sendFPScmd "setval mfilt-${CACAO_LOOPNUMBER}.AOloopindex ${CACAO_LOOPNUMBER}"
	sendFPScmd "setval mfilt-${CACAO_LOOPNUMBER}.comp.latencyhardwfr ${CACAO_LATENCYHARDWFR}"
	sendFPScmd "setval mfilt-${CACAO_LOOPNUMBER}.comp.OLmodes ON"
	sendFPScmd "setval mfilt-${CACAO_LOOPNUMBER}.comp.tbuff ON"
	sendFPScmd "confwupdate mfilt-${CACAO_LOOPNUMBER}"
	sendFPScmd "runstart mfilt-${CACAO_LOOPNUMBER}"
fi


if [ ${ACTION} == "stop" ]; then
	ACTIONOK=1
	cacaomsglog "STOP"
	sendFPScmd "runstop mfilt-${CACAO_LOOPNUMBER}"
fi




if [ ${ACTIONOK} == 0 ]; then
	echo "[$(tput setaf 1)$(tput bold) FAILED $(tput sgr0)] ACTION $ACTION undefined"
	cacaomsglog "ERROR ACTION undefined"
fi

cacaomsglog "END"
