#!/usr/bin/env bash

# This script uses milk-argparse
# See template milk-scriptexample in module milk_module_example for template and instructions

# script 1-line description
MSdescr="WFS reference optimization from PSF stream"

MSextdescr="Optimize WFS reference from PSF stream

Processes filesystem telemetry:
- PSF (CACAO_PSFSTREAM)
- WFS (CACAO_WFSSTREAM)
- DM (dmXXdisp)
These 3 streams must be recorded.

WFS telemetry location:
CACAO_TELEMETRY_LOGDIR/YYYYMMDD/

By default, timestart for the optimization is current time at script launch.
Can be overriden with ts option

"

source milk-script-std-config
source cacao-check-cacaovars

MSarg+=( "tspan:float:time span [s]" )
MSarg+=( "tint:float:integration time per sample" )


# UNIX time at start
#
TIMESTART=$(date +%s)
echo "TIMESTART = ${TIMESTART}"
#UTDAY=$(date -u '+%Y%m%d')
MSopt+=( "ts:tstart:set_timestart:TIMESTART[long]:set time start [unix tstamp]" )
function set_timestart() {
	TIMESTART="$1"
	echo "Setting TIMESTART to ${TIMESTART}"
}


# logdir
#
LOGDIR="${CACAO_TELEMETRY_LOGDIR}"
MSopt+=( "l:logdir:set_logdir:LOGDIR[string]:set log directory from which to read telemetry" )
function set_logdir() {
	LOGDIR="$1"
}


# PSF crop window
#
PSFCROP="*,*"
MSopt+=( "pc:PSFcrop:set_PSFcrop:PSFcrop[string]:PSF crop window x1,x2\:y1,y2" )
function set_PSFcrop() {
	PSFCROP="$1"
}



source milk-argparse
TSPAN="${inputMSargARRAY[0]}"
TINT="${inputMSargARRAY[1]}"

UTDAY=$(date -u -d @$TIMESTART +%Y%m%d)

echo "LOGDIR    : ${LOGDIR}"
echo "TIMESTART : ${TIMESTART}"
echo "UTDAY     : ${UTDAY}"





# Checking FPS
FPScheckOK="OK"

cacaomsglog "START"

WDIR="wdir_wfsrefoptpsf"

streamWFSdir=${LOGDIR}/${UTDAY}/${CACAO_WFSSTREAM}
streamPSFdir=${LOGDIR}/${UTDAY}/${CACAO_PSFSTREAM}
streamDMdir=${LOGDIR}/${UTDAY}/dm${CACAO_DMINDEX}disp


EXITSTATUS=0

checkDir ${streamWFSdir}
checkDir ${streamPSFdir}
checkDir ${streamDMdir}

if [ ${EXITSTATUS} = 1 ]; then
	echo "missing file - cannot proceed"
	exit 1
fi



# 1: stream name
# 2: file name (basename)
# 3: 2D crop window, "x1:x2,y1:y2", or "*:*"
function processcube()
{
	PTAG=".proc"
	INFILE="${LOGDIR}/${UTDAY}/$1/$2.fits"
	OUTFILE=${UTDAY}/$1/$2${PTAG}.fits
	mkdir -p ${UTDAY}/$1
	echo "Processing $INFILE -> $OUTFILE"

	if [ ! -f ${OUTFILE} ]; then
milk-all << EOF
loadfits "${INFILE}[$3,*]" imc
loadfits "$1.dark.fits[$3]" imd
imcd=imc-imd
saveFITS imcd "${OUTFILE}"
listim
exitCLI
EOF
	fi
}





# find last timing files in telemetry directories

echo "WFSdir = ${streamWFSdir}"

mkdir -p ${WDIR}
cd ${WDIR}

iter=0
NBiter=100

while [ ${iter} -ne ${NBiter} ] ; do
	echo ""
	echo "ITERATION ${iter}"
	let iter++ || :


set +e
# allow for error as timing files are either .dat or .txt, not both
ls ${streamWFSdir}/*.txt 2> /dev/null | tail -n 1
lastLogFileWFS=$( ls ${streamWFSdir}/*.txt 2> /dev/null | tail -n 1 )
echo "Last WFS file = ${lastLogFileWFS}"
cp $lastLogFileWFS _lastlogfileWFS

echo "PSFdir = ${streamPSFdir}"
ls ${streamPSFdir}/*.txt 2> /dev/null | tail -n 1
lastLogFilePSF=$( ls ${streamPSFdir}/*.txt 2> /dev/null | tail -n 1 )
echo "Last PSF file = ${lastLogFilePSF}"
cp $lastLogFilePSF _lastlogfilePSF
set -e


let "TIMEEND = TIMESTART + TSPAN"

echo "TIME : ${TIMESTART} + ${TSPAN} -> ${TIMEEND} ====================================="



# vOK is 1 if files need to be processed
# 0 if no input files to be processed
vOK="1"




lastLogTimeWFS=$( cat _lastlogfileWFS | tail -n 1 | awk '{print int($4)}' )
echo "WFS last log at $lastLogTimeWFS"

if [ "${lastLogTimeWFS}" -lt "${TIMEEND}" ]; then
	vOK="0"
	echo "last WFS has not reached time end yet!"
	echo "${lastLogTimeWFS} < ${TIMEEND}"
fi


lastLogTimePSF=$( cat _lastlogfilePSF | tail -n 1 | awk '{print int($4)}' )
echo "PSF last log at $lastLogTimePSF"

if [ "${lastLogTimePSF}" -lt "${TIMEEND}" ]; then
	vOK="0"
	echo "last PSF has not reached time end yet!"
	echo "${lastLogTimePSF} < ${TIMEEND}"
fi


if [ "$vOK" = "1" ]; then



# PROCESS PSF FILES

# file list
for fname in ${LOGDIR}/${UTDAY}/${CACAO_PSFSTREAM}/*.txt; do
	#echo "scanning file $fname"
	filetstart=$( sed /^#/d $fname | sed -n 1p | awk '{print int($4)}' )
	filetend=$( cat $fname | tail -n 1 | awk '{print int($4)}' )
	#echo "   time : $filetstart -> $filetend"

	if (( $(echo "$filetstart < $TIMEEND" |bc -l) )); then
	if (( $(echo "$filetend > $TIMESTART" |bc -l) )); then
		fname1=${fname%.txt}
		fname2=${fname1##*/}
		echo "PROCESSING ${fname2}"
		cp $fname ./${UTDAY}/${CACAO_PSFSTREAM}/
		processcube ${CACAO_PSFSTREAM} ${fname2} "${PSFCROP}"
	fi
	fi
done




# PROCESS WFS FILES
for fname in ${LOGDIR}/${UTDAY}/${CACAO_WFSSTREAM}/*.txt; do
	#echo "scanning file $fname"
	filetstart=$( sed /^#/d $fname | sed -n 1p | awk '{print int($4)}' )
	filetend=$( cat $fname | tail -n 1 | awk '{print int($4)}' )
	#echo "   time : $filetstart -> $filetend"

	if (( $(echo "$filetstart < $TIMEEND" |bc -l) )); then
	if (( $(echo "$filetend > $TIMESTART" |bc -l) )); then
		fname1=${fname%.txt}
		fname2=${fname1##*/}
		echo "PROCESSING ${fname2}"
		cp $fname ./${UTDAY}/${CACAO_WFSSTREAM}/
		processcube ${CACAO_WFSSTREAM} ${fname2} "*,*"
	fi
	fi
done



cacao << EOF
cacaopt.slogtsample .logdir "."
cacaopt.slogtsample .s0name ${CACAO_PSFSTREAM}
cacaopt.slogtsample .s0tag ".proc"
cacaopt.slogtsample .s1name ${CACAO_WFSSTREAM}
cacaopt.slogtsample .s1tag ".proc"
cacaopt.slogtsample .tstartnsec 0
cacaopt.slogtsample .tendnsec 0
cacaopt.slogtsample ?
cacaopt.slogtsample ${TIMESTART} ${TIMEEND} ${TINT}
listim
saveFITS ${CACAO_PSFSTREAM} "${CACAO_PSFSTREAM}.sync.fits"
saveFITS ${CACAO_WFSSTREAM} "${CACAO_WFSSTREAM}.sync.fits"
exitCLI
EOF


cacao << EOF
loadfits "${CACAO_WFSSTREAM}.sync.fits" wfsimc
loadfits "${CACAO_PSFSTREAM}.sync.fits" psfimc
cacaopt.wfsroptsel .selnormplaw 4.0
cacaopt.wfsroptsel psfimc wfsimc
saveFITS psf_sorted "psf_sorted.fits"
saveFITS wfs_sorted "wfs_sorted.fits"
saveFITS wfsrefopt "wfsrefopt.fits"
listim
exitCLI
EOF



# exit loop
iter=${NBiter}
fi


sleep 2.0

done



cd ..


cacaomsglog "END"
