#!/usr/bin/env bash

# This script uses milk-argparse
# See template milk-scriptexample in module milk_module_example for template and instructions

# script 1-line description
MSdescr="Take WFS camera dark frame"


# Extended description
MSextdescr="Reads from aolX_wfsim stream
Averages a number of frames
Saes into stream aolX_wfsdarkraw
Make aolX_wfsdark sym link pointer to aolX_wfsdarkraw
Saves dark as conf/aolX_wfsdarkraw.fits"


source milk-script-std-config
source cacao-check-cacaovars



NBframe="1000"
MSopt+=( "n:nbframe:set_NBframe:nbframe[long]:set number of frames" )
function set_NBframe() {
	NBframe="$1"
}

source milk-argparse


# Checking stream
streamcheckOK="OK"
checkstream aol${CACAO_LOOPNUMBER}_wfsim

if [ ${streamcheckOK} == "FAIL" ]; then
	echo "[$(tput setaf 1)$(tput bold) FAILED $(tput sgr0)] stream check failed"
	cacaomsglog "ERROR streamcheck"
	exit 1
fi

cacaomsglog "NBframe ${NBframe}"


# ======================================================================
# Turning source off
# ======================================================================


set +u
if [ -z ${CACAO_FPSPROC_WFSCAMSIM+x} ]; then
	echo "CACAO_FPSPROC_WFSCAMSIM does not exist"
else

if [ $CACAO_FPSPROC_WFSCAMSIM = "ON" ]; then
	echo "CACAO_FPSPROC_WFSCAMSIM set -> simulator"
	sendFPScmd "setval wfscamsim-${CACAO_LOOPNUMBER}.fluxtotal 0.0"
else
	echo "CACAO_FPSPROC_WFSCAMSIM not set -> no simulator"
fi

fi
set -u

sleep 1

mkdir -p conf

datestring="$(date -u +'%Y-%m-%dT%H:%M:%S.%NZ')"

cacaomsglog "START acquisition"
MILK_QUIET=1 milk << EOF
readshmim aol${CACAO_LOOPNUMBER}_wfsim
streamave ..procinfo 1
streamave ..triggersname aol${CACAO_LOOPNUMBER}_wfsim
streamave ..triggermode 3
streamave ..loopcntMax ${NBframe}
streamave aol${CACAO_LOOPNUMBER}_wfsim imdark ${NBframe}
saveFITS imdark "conf/wfsdarkraw.${datestring}.fits"
cpsh imdark aol${CACAO_LOOPNUMBER}_wfsdarkraw
listim
exitCLI
EOF
cacaomsglog "STOP acquisition"
cacaomsglog "SAVED wfsdarkraw as conf/wfsdarkraw.${datestring}.fits"


cacaomsglog "SAVING to logdir"
LOGDIR="logdir/$(date -u +'%Y%m%d')/aol_${CACAO_LOOPNAME}/wfsdarkraw/"
daystring="$(date -u +'%Y%m%d')"
mkdir -p ${LOGDIR}
cacaomsglog "cp conf/wfsdarkraw.${datestring}.fits ${LOGDIR}/"
cp conf/wfsdarkraw.${datestring}.fits ${LOGDIR}/



# by default, link dark to raw dark (may be overridden if mapping)
cacaomsglog "SETTING wfsdark as wfsdarkraw.${datestring}.fits"

rm -f ${MILK_SHM_DIR}/aol${CACAO_LOOPNUMBER}_wfsdark.im.shm
ln -s ${MILK_SHM_DIR}/aol${CACAO_LOOPNUMBER}_wfsdarkraw.im.shm ${MILK_SHM_DIR}/aol${CACAO_LOOPNUMBER}_wfsdark.im.shm 

# ======================================================================
# Turning source on
# ======================================================================

set +u

if [ -z ${CACAO_FPSPROC_WFSCAMSIM+x} ]; then
	echo "CACAO_FPSPROC_WFSCAMSIM does not exist"
else
	if [ $CACAO_FPSPROC_WFSCAMSIM = "ON" ]; then
		FLUX=${CACAO_FPS_wfscamsim_fluxtotal:-100000}
		sendFPScmd "setval wfscamsim-${CACAO_LOOPNUMBER}.fluxtotal ${FLUX}"
	else
		echo "CACAO_FPSPROC_WFSCAMSIM not set -> no simulator"
	fi
fi

set -u

cacaomsglog "END"
