#!/bin/bash


# ======================================================================
# STANDARD CACAOTASK HEADER
# CHECK THAT THIS SCRIPT IS EXECUTED IN A CACAOTASK ENVIRONMENT
# ======================================================================


# FATAL exit code
CACAOTASK_EXITCODE_NOTCACAOTASK=64

#
# Check that this script is executed from cacaotask
# If not, print error message and exit
#
function taskerrormsg {
  echo "ERROR: This is a cacaotask script"
  echo "       It is meant to be executed as part of a deployment script"
  echo "       Check cacaotask script for details"
}

#echo "cacaotaskENV : ${cacaotaskENV}"
if [ ! "${cacaotaskENV:-}" = "OK" ]; then
  taskerrormsg
  echo "Exiting script $0"
  exit ${CACAOTASK_EXITCODE_NOTCACAOTASK}
fi

