#!/bin/bash

# check environment
source cacaotask-check



# ======================================================================
# PERFORM ACTIONS FOR THIS TASK
# ======================================================================

mkdir -p ${WORKDIRECTORY}

# check if successful
if [ "$?" = 0 ]; then
	cacaotask_RETURNCODE=${CACAOTASK_RUN_SUCCESS}
else
	cacaotask_RETURNCODE=${CACAOTASK_RUN_FAIL}
fi



# ======================================================================
# WRITE CLEANUP SCRIPT FOR THIS TASK
# ======================================================================

# Inside cat <<EOT section :
# ${VAR} will be resolved prior to writing to destination
# \${VAR} will not be resolved, and will appear as ${VAR} in the destination
#
cat <<EOT >>  ${CLEANSCRIPT}

read -p "REMOVING directory ./\${WORKDIRECTORYLOCAL}. Are you sure? " -n 1 -r
echo
if [[ \${REPLY} =~ ^[Yy]$ ]]
then
    rm -r ./\${WORKDIRECTORYLOCAL}
fi

EOT



# ======================================================================
# STORE OUTPUT ENVIRONMENT VARIABLES
# ======================================================================

# NEWVAR_INITSETUP=2
# echo "NEWVAR_INITSETUP=${NEWVAR_INITSETUP}" >> ${ENVOUTFILE}

