#!/bin/bash

# number of arguments to script
NBARGS=0


srcdir="$PWD"

if [ -f .scripts_src_dir.conf ]; then
srcdir=$( cat .scripts_src_dir.conf )
fi


# ======================= PROCESS NAME =================================
pname=`echo "$0" | sed "s/\.\///g"`
echo "pname = $pname"



filelist="aolconf"
dirlist="aolconfscripts auxscripts aohardsim aocscripts aosetup aolfuncs dmutils"

printHELP ()
{
echo "------------------------------------------------------------------------"
echo "$(tput bold) $pname : SYNC AOloopControl scripts $(tput sgr0)"
echo "------------------------------------------------------------------------"
echo "  "
echo " $(tput bold)USAGE:$(tput sgr0)"
echo "     $0 [-hcs]"
echo ""
echo " $(tput bold)OPTIONS:$(tput sgr0)"
echo "     $(tput bold)-h$(tput sgr0)              (h)elp"
echo "     $(tput bold)-e$(tput sgr0) <DESTdir>    (e)xport syncscript to directory"
echo "     $(tput bold)-s$(tput sgr0) <SRCdir>     (s)ource directory for scripts"
echo "     $(tput bold)-d$(tput sgr0)              har(d) copy instead of symbolic link"
echo "     $(tput bold)-c$(tput sgr0)              (c)lear all files in directory (USE WITH CARE)"
echo ""
echo "------------------------------------------------------------------------"
}
	




# ================= OPTIONS =============================

HARD="0"

while getopts :hcs:e:d FLAG; do
  case $FLAG in
    h)  #show help
      printHELP
      exit
      ;;
    s) # source directory
    srcdir="$OPTARG"
    ;;
    c) # clear
    echo "Clearing all directory and files"
    ls | grep -v syncscripts | xargs rm -rf
    ;;
    e) # export script to directory
    echo "$PWD" > $OPTARG/.scripts_src_dir.conf
    rm $OPTARG/syncscripts 2> /dev/null
    ln -s $PWD/syncscripts $OPTARG/syncscripts
    execname=$( ls $PWD/../../../bin/ )
    rm $OPTARG/AOloopControl 2> /dev/null
    echo "execname = \"$execname\""
    #ln -s $PWD/../../../bin/$execname $OPTARG/AOloopControl
    ln -s /usr/local/bin/cacao $OPTARG/AOloopControl
    exit
    ;;
    d)
    HARD="1"
    ;;
    \?) #unrecognized option - show help
      echo -e \\n"Option -${BOLD}$OPTARG${NORM} not allowed."
      printHELP
      ;;
  esac
done

	
shift $((OPTIND-1))





if [ "$1" = "help" ] || [ "$#" -ne $NBARGS ]; then
if [ "$#" -ne $NBARGS ]; then
    echo "$(tput setaf 1)$(tput bold) Illegal number of parameters ($NBARGS params required, $# entered) $(tput sgr0)"
fi
printHELP
        exit
fi
	
	






echo ""
echo "SYNCING AOloopControl scripts..."
echo ""


for file in ${filelist[*]}
do
	srcfile="$srcdir/$file"
	echo "syncing file $srcfile -> $file"
	ln -fs $srcfile $file	
done



for dir in ${dirlist[*]}
do
	mkdir -p $dir
	srcdir1="$srcdir/$dir"
	echo ""
	echo "syncing directory $srcdir1"

	for entry in $srcdir1/*
	do
	if [ ! -d $entry ]; then
		filename="${entry##*/}"	
		echo "   syncing directory $srcdir1 file $filename"
		if [ $HARD -eq 1 ]; then
		cp $entry ./$dir/$filename
		else
		ln -fs $entry ./$dir/$filename
		fi
	fi
	done

done



echo ""

