#!/bin/bash


# number of arguments to script
NBARGS=0







function printHELP {
echo "------------------------------------------------------------------------"
echo "$(tput bold) GENERATE ATMOSPHERIC WAVEFRONTS $(tput sgr0)"
echo "------------------------------------------------------------------------"
echo "  Create WF series"
echo "   "
echo " $(tput bold)USAGE:$(tput sgr0)"
echo "     $0 [-h]"
echo ""
echo " $(tput bold)OPTIONS:$(tput sgr0)"
echo "     $(tput bold)-h$(tput sgr0)          help"
echo ""
echo ""
echo "------------------------------------------------------------------------"
}


printHELP1 ()
{
    printf "%20s       Create WF series\n" "$0"
}



EXITSTATUS=0



# ================= OPTIONS =============================




# Transform long options to short ones
singlelinehelp=0
for arg in "$@"; do
  shift
  case "$arg" in
    "--help") set -- "$@" "-h" ;;
    "--help1")
set -- "$@" "-h"
singlelinehelp=1;
;;
    *)        set -- "$@" "$arg"
  esac
done




while getopts :hH:L:N:Cc FLAG; do
  case $FLAG in
    h)  #show help
      if [ "$singlelinehelp" -eq "0" ]; then
      printHELP
      else
      printHELP1
      fi
      exit
      ;;

    \?) #unrecognized option - show help
      echo -e \\n"Option -${BOLD}$OPTARG${NORM} not allowed."
      printHELP
      ;;
  esac
done

shift $((OPTIND-1))









if [ "$1" = "help" ] || [ "$#" -ne $NBARGS ]; then
if [ "$#" -ne $NBARGS ]; then
    echo "$(tput setaf 1)$(tput bold) Illegal number of parameters ($NBARGS params required, $# entered) $(tput sgr0)"
fi
printHELP
        exit
fi








if [ $EXITSTATUS -eq 1 ]; then
echo ""
echo "$(tput setaf 1)$(tput bold) REQUIRED FILES, COMMANDS NOT FOUND: EXITING $(tput sgr0)"
echo ""
exit
else
echo ""
fi




# ======================= SCRIPT CODE STARTS HERE =================================





srcdir=$( cat .scripts_src_dir.conf )
mkdir atmwf
cp $srcdir/../../AtmosphericTurbulence/scripts/runturb ./atmwf/
cd atmwf
./runturb -e ../AOloopControl 1.650
