#!/usr/bin/env bash

# This script uses milk-argparse
# See template milk-scriptexample in module milk_module_example for template and instructions


MSdescr="make DM poke modes"

MSextdescr="Make DM poke modes for response matrix acquisition"

source milk-script-std-config
source cacao-check-cacaovars


source milk-argparse



echo "DM size  : $CACAO_DMxsize x $CACAO_DMysize"


DMMODEDIR="conf/DMmodes"
mkdir -p ${DMMODEDIR}



x0default=$(echo "scale=3; $CACAO_DMxsize/2" | bc)
y0default=$(echo "scale=3; $CACAO_DMysize/2" | bc)
r0default=$(echo "scale=3; 0.450*$CACAO_DMxsize" | bc)



DMx0=${CACAO_DM_beam_xcent:-$x0default}
DMy0=${CACAO_DM_beam_ycent:-$y0default}
DMr0=${CACAO_DM_beam_rad:-$r0default}

echo "using DMx0 = ${DMx0}"
echo "using DMy0 = ${DMy0}"
echo "using DMr0 = ${DMr0}"




# Make DM mask if it doesn't exist

cacao << EOF
imgen.mkdisk DMmask ${CACAO_DMxsize} ${CACAO_DMysize} ${DMx0} ${DMy0} ${DMr0}
saveFITS DMmask "${DMMODEDIR}/DMmask.fits"
listim
exitCLI
EOF



# Hadamard modes

cacao << EOF
loadfits "${DMMODEDIR}/DMmask.fits" DMmask
cacaocc.mkHadamard DMmask HpokeC
saveFITS HpokeC "${DMMODEDIR}/HpokeC.fits"
saveFITS Hpixindex "${DMMODEDIR}/Hpixindex.fits"
saveFITS Hmat "${DMMODEDIR}/Hmat.fits"
listim
exitCLI
EOF



# Fourier modes


CPAmax=8.0
deltaCPA=0.8



cacao << EOF
lintools.mkFouriermodes Fmodes ${CACAO_DMxsize} ${CACAO_DMysize} ${CPAmax} ${deltaCPA} ${DMr0} 1.1 0
saveFITS Fmodes "${DMMODEDIR}/Fmodes.fits"
listim
exitCLI
EOF
