#!/usr/bin/env bash

# This script uses milk-argparse
# See template milk-scriptexample in module milk_module_example for template and instructions


MSdescr="make DM poke modes"

set +u
if [ -z ${CACAO_CONFWDIR+x} ]; then
	CACAO_CONFWDIR="conf"
fi
set -u

MSextdescr="Make DM poke modes for response matrix acquisition

CACAO_CONFWDIR
Optional: Use CACAO_CONFWDIR to select directory
Default: ./conf/

INPUT (optional)

  <CACAO_CONFWDIR>/RMmodesDM/DMmask.fits
	DM mask. Value=1 for active actuators, 0 otherwise
	Will be created if it does not exist, assuming all actuators active.

OUTPUT

  <CACAO_CONFWDIR>/RMmodesDM/FpokesC.<CPAmax>.fits
	Fourier modes, up to cycles per aperture = <CPAmax>

  <CACAO_CONFWDIR>/RMmodesDM/ZpokesC.<NBzer>.fits
	Zerkine mode, up to index <NBzer>

  <CACAO_CONFWDIR>/RMmodesDM/HpokeC.fits
  <CACAO_CONFWDIR>/RMmodesDM/Hpixindex.fits
  <CACAO_CONFWDIR>/RMmodesDM/Hmat.fits
	Hadamard modes, full complement.
	HpokeC    : modes
	Hpixindex : actuator index
	Hmat      : encoding/decoding matrix


Writes DM poke matrices to ./<CACAO_CONFWDIR>/RMmodesDM/ directory

Creates DM modes with minimal assumptions or knowledge of the optical sytem.
This is typically the starting point of a calibration, used to define poke modes to probe the system.
"

source milk-script-std-config
source cacao-check-cacaovars


# SCRIPT OPTIONS
# syntax: "short:long:functioncall:args[types]:description"

MSopt+=( "c:CPAmax:setCPAmax:cpamax[float]:Set maximum cycles per aperture (CPA) [8]" )
CPAmax="8"
function setCPAmax()
{
	CPAmax=$1
}

MSopt+=( "z:NBzer:setNBzer:NBzer[int]:Set number of Zernike polynomials [5]" )
NBzer=5
function setNBzer()
{
	NBzer=$1
}



source milk-argparse



echo "DM size  : $CACAO_DMxsize x $CACAO_DMysize"
echo "DM spatial : $CACAO_DMSPATIAL"
if [ "$CACAO_DMSPATIAL" == "0" ]; then
	# This is not a spatial DM, make a very large radius so that
	# All actuators are considered regardless
	# Note: we expect CACAO_DMxsize = n_actuators and CACAO_DMysize=1
	CACAO_DM_beam_rad=$CACAO_DMxsize
	echo "CACAO_DM_beam_rad: ${CACAO_DM_beam_rad}"
fi

DMMODEDIR="${CACAO_CONFWDIR}/RMmodesDM"
mkdir -p ${DMMODEDIR}


# These 2 are not the buffer center and need a 0.5 offset...
# (although that depends on the implementation of imgen.mkdisk)
x0default=$(echo "scale=3; $CACAO_DMxsize/2" | bc)
y0default=$(echo "scale=3; $CACAO_DMysize/2" | bc)
#r0default=$(echo "scale=3; 0.450*$CACAO_DMxsize" | bc)
r0default=$(echo "scale=3; $CACAO_DMxsize" | bc)



DMx0=${CACAO_DM_beam_xcent:-$x0default}
DMy0=${CACAO_DM_beam_ycent:-$y0default}
DMr0=${CACAO_DM_beam_rad:-$r0default}

echo "using DMx0 = ${DMx0}"
echo "using DMy0 = ${DMy0}"
echo "using DMr0 = ${DMr0}"




# Make DM mask if it doesn't exist

if [ -f "${DMMODEDIR}/DMmask.fits" ]; then
echo "Using existing DMmask"
else
echo "Creating DMmask"
cacao << EOF
imgen.mkdisk DMmask ${CACAO_DMxsize} ${CACAO_DMysize} ${DMx0} ${DMy0} ${DMr0}
saveFITS DMmask "${DMMODEDIR}/DMmask.fits"
listim
exitCLI
EOF
fi

# Simple zonal modes
# command aolmksimplezpM no longer exists
#cacao << EOF
#loadfits "${DMMODEDIR}/DMmask.fits" DMmask
#cacaoct.aolmksimplezpM ${CACAO_DMxsize} ${CACAO_DMysize} Spoke
#saveFITS Spoke "${DMMODEDIR}/SmodesC.fits"
#exitCLI
#EOF


# Hadamard modes

cacao << EOF
loadfits "${DMMODEDIR}/DMmask.fits" DMmask
cacaocc.mkHadamard DMmask HpokeC
saveFITS HpokeC "${DMMODEDIR}/HpokeC.fits"
saveFITS Hpixindex "${DMMODEDIR}/Hpixindex.fits"
saveFITS Hmat "${DMMODEDIR}/Hmat.fits"
listim
exitCLI
EOF



# Fourier modes

deltaCPA=0.8

cacao << EOF
lintools.mkFouriermodes Fmodes ${CACAO_DMxsize} ${CACAO_DMysize} ${CPAmax} ${deltaCPA} ${DMr0} 1.1 0
saveFITS Fmodes "${DMMODEDIR}/FpokesC.${CPAmax}.fits"
listim
exitCLI
EOF


# Zernike modes

milk-all << EOF
zern.mkzerc zerc ${CACAO_DMxsize} ${CACAO_DMysize} ${DMx0} ${DMy0} ${DMr0} ${NBzer}
saveFITS zerc "${DMMODEDIR}/ZpokesC.${NBzer}.fits"
listim
exitCLI
EOF
