#!/usr/bin/env bash

# This script uses milk-argparse
# See milk-scriptexample for template and instructions

# script 1-line description
MSdescr="set hardware configuration"

MSextdescr="Hardware mode
"

source milk-script-std-config
source cacao-check-cacaovars

RequiredCommands=( cacao-setDMnolink )

source milk-argparse



# Checking required FPS
FPScheckOK="OK"
checkFPSON CACAO_FPSPROC_ACQUWFS ${CACAO_FPSPROC_ACQUWFS}
checkFPSON CACAO_FPSPROC_MVMGPU_WFS2CMODEVAL ${CACAO_FPSPROC_MVMGPU_WFS2CMODEVAL}
checkFPSON CACAO_FPSPROC_MODALFILTERING ${CACAO_FPSPROC_MODALFILTERING}
checkFPSON CACAO_FPSPROC_MVMGPU_CMODEVAL2DM ${CACAO_FPSPROC_MVMGPU_CMODEVAL2DM}
checkFPSON CACAO_FPSPROC_MEASURELINRESP ${CACAO_FPSPROC_MEASURELINRESP}

if [ ${FPScheckOK} == "FAIL" ]; then
	echo "[$(tput setaf 1)$(tput bold) FAILED $(tput sgr0)] FPS check failed"
	cacaomsglog "ERROR FPScheck"
	exit 1
fi





sendFPScmd "setval measlinresp-${CACAO_LOOPNUMBER}.ampl 0.03"
sendFPScmd "setval measlinresp-${CACAO_LOOPNUMBER}.timing.NBave 5"
sendFPScmd "setval measlinresp-${CACAO_LOOPNUMBER}.timing.NBexcl 1"
sendFPScmd "setval measlinresp-${CACAO_LOOPNUMBER}.timing.NBinnerCycle 10"
sendFPScmd "setval measlinresp-${CACAO_LOOPNUMBER}.procinfo.loopcntMax 40"


sendFPScmd "setval wfs2cmodeval-${CACAO_LOOPNUMBER}.GPUindex 1"
sendFPScmd "confwupdate wfs2cmodeval-${CACAO_LOOPNUMBER}"

sendFPScmd "setval mvalC2dm-${CACAO_LOOPNUMBER}.GPUindex 1"
sendFPScmd "confwupdate mvalC2dm-${CACAO_LOOPNUMBER}"


sendFPScmd "setval compstrCM-${CACAO_LOOPNUMBER}.svdlim 0.01"


# WFS
echo "Linking WFS"

ln -sf ${MILK_SHM_DIR}/${CACAO_WFSSTREAM}.im.shm ${MILK_SHM_DIR}/aol${CACAO_LOOPNUMBER}_wfsim.im.shm

sendFPScmd "setval acquWFS-${CACAO_LOOPNUMBER}.insname aol${CACAO_LOOPNUMBER}_wfsim"
sendFPScmd "setval acquWFS-${CACAO_LOOPNUMBER}.WFSnormfloor 0.1"
sendFPScmd "confwupdate acquWFS-${CACAO_LOOPNUMBER}"

# DM

echo "Switching to hardware DM"
DMINDEX="${CACAO_DMINDEX}"
echo "${DMINDEX}" > DMINDEX

echo "Linking DM"
cacao-setDMnolink

sendFPScmd "setval DMch2disp-${DMINDEX}.AveMode 1"
sendFPScmd "setval DMch2disp-${DMINDEX}.option.voltmode ON"
sendFPScmd "setval DMch2disp-${DMINDEX}.option.volttype 2"
sendFPScmd "setval DMch2disp-${DMINDEX}.option.stroke100 1.0"
sendFPScmd "setval DMch2disp-${DMINDEX}.option.voltname dmvolt"
sendFPScmd "setval DMch2disp-${DMINDEX}.option.DClevel 0.7"
sendFPScmd "setval DMch2disp-${DMINDEX}.option.maxvolt 150.0"
sendFPScmd "confwupdate DMch2disp-${DMINDEX}"



# update system cacaoloop record
#
CACAOLOOPRECORD="${MILK_SHM_DIR}/cacaoloop-${CACAO_LOOPNUMBER}"
mkdir -p ${CACAOLOOPRECORD}
echo "${DMINDEX}" > ${CACAOLOOPRECORD}/dmindex
echo "${CACAO_WFSSTREAM}" > ${CACAOLOOPRECORD}/wfsim


cacaomsglog "END"
