#!/usr/bin/env bash


MSdescr="Set pyramid reference to flat"

MSextdescr="
"


source milk-script-std-config
source cacao-check-cacaovars


source milk-argparse



cacaomsglog "START"

milk << EOF
readshmim aol${CACAO_LOOPNUMBER}_wfsmask
wfsm=0+aol${CACAO_LOOPNUMBER}_wfsmask
wfsmn=wfsm/itot(wfsm)
#saveFITS wfsmn "wfsm.fits"
readshmim aol${CACAO_LOOPNUMBER}_wfsrefc
cpsh wfsmn aol${CACAO_LOOPNUMBER}_wfsrefc
exitCLI
EOF

cacaomsglog "EXIT"
