#!/usr/bin/env bash

# add column_sum function to fpsCTRL

source ./scripts/fps-utility

# name of function to setup
fname="norm_spectra"

# add to fpsCTRL, start tmux, start conf, turn on procinfo
setupfps "${fname}"

# procinfo specific stuff
sendFPScmd "setval ${fname}-${CACAO_LOOPNUMBER}.procinfo.triggermode 3"
sendFPScmd "setval ${fname}-${CACAO_LOOPNUMBER}.procinfo.loopcntMax -1"
sendFPScmd "setval ${fname}-${CACAO_LOOPNUMBER}.procinfo.triggersname aol${CACAO_LOOPNUMBER}_imWFS2"

# setting input and output streams
sendFPScmd "setval ${fname}-${CACAO_LOOPNUMBER}.wfsin aol${CACAO_LOOPNUMBER}_imWFS2"
sendFPScmd "setval ${fname}-${CACAO_LOOPNUMBER}.wfsout aol6_imWFS2_norm" 

sendFPScmd "confwupdate ${fname}-${CACAO_LOOPNUMBER}"
