#!/usr/bin/env bash

# find spectral traces and write to shm called 'aolx_wfsspecmask'
# run in rootdir

source cacao-check-cacaovars

(
cd scripts

python << EOF
import os
import utility
num = os.getenv("CACAO_LOOPNUMBER")
outshmname = "aol"+str(num)+"_wfsspecmask"
utility.make_spectral_mask("apapanesim",outshmname)
EOF
)