#!/usr/bin/env bash

# This script uses milk-argparse
# See template milk-scriptexample in module milk_module_example for template and instructions

# script 1-line description
MSdescr="remap WFS dark frame"

MSextdescr="Remaps dark according to mapping file"

source milk-script-std-config
source cacao-check-cacaovars

source milk-argparse




# average #NBAVE frames, write result to conf/wfsimave.fits

rm ${MILK_SHM_DIR}/aol${CACAO_LOOPNUMBER}_wfsdark.im.shm
cacao << EOF
loadfits "conf/aol${CACAO_LOOPNUMBER}_wfsdarkraw.fits" darkraw
loadfits "conf/spotmap.fits" spotmap
cacaoio.mapWFS darkraw spotmap darkm
saveFITS darkm "conf/aol${CACAO_LOOPNUMBER}_wfsdark.fits"
cpsh darkm aol${CACAO_LOOPNUMBER}_wfsdark
exitCLI
EOF

