var annotated =
[
    [ "__attribute__", "struct____attribute____.html", "struct____attribute____" ],
    [ "AOLOOPCONTROL_CONF", "structAOLOOPCONTROL__CONF.html", "structAOLOOPCONTROL__CONF" ],
    [ "AOLOOPCONTROL_DM_DISPCOMB_CONF", "structAOLOOPCONTROL__DM__DISPCOMB__CONF.html", "structAOLOOPCONTROL__DM__DISPCOMB__CONF" ],
    [ "AOLOOPCONTROL_DMTURBCONF", "structAOLOOPCONTROL__DMTURBCONF.html", "structAOLOOPCONTROL__DMTURBCONF" ],
    [ "BITMAPFILEHEADER", "structBITMAPFILEHEADER.html", "structBITMAPFILEHEADER" ],
    [ "BITMAPINFOHEADER", "structBITMAPINFOHEADER.html", "structBITMAPINFOHEADER" ],
    [ "CMD", "structCMD.html", "structCMD" ],
    [ "CMDARGTOKEN", "structCMDARGTOKEN.html", "structCMDARGTOKEN" ],
    [ "complex_double", "structcomplex__double.html", "structcomplex__double" ],
    [ "complex_float", "structcomplex__float.html", "structcomplex__float" ],
    [ "DATA", "structDATA.html", "structDATA" ],
    [ "FPAOLOOPCONTROL_CONF", "structFPAOLOOPCONTROL__CONF.html", "structFPAOLOOPCONTROL__CONF" ],
    [ "GPUMATMULTCONF", "structGPUMATMULTCONF.html", "structGPUMATMULTCONF" ],
    [ "kdhyperrect", "structkdhyperrect.html", "structkdhyperrect" ],
    [ "kdnode", "structkdnode.html", "structkdnode" ],
    [ "kdres", "structkdres.html", "structkdres" ],
    [ "kdtree", "structkdtree.html", "structkdtree" ],
    [ "LOGSHIM_CONF", "structLOGSHIM__CONF.html", "structLOGSHIM__CONF" ],
    [ "MODULE", "structMODULE.html", "structMODULE" ],
    [ "res_node", "structres__node.html", "structres__node" ],
    [ "savethreadmsg", "structsavethreadmsg.html", "structsavethreadmsg" ],
    [ "sImage", "structsImage.html", "structsImage" ],
    [ "symrec", "structsymrec.html", "structsymrec" ],
    [ "TCP_BUFFER_METADATA", "structTCP__BUFFER__METADATA.html", "structTCP__BUFFER__METADATA" ],
    [ "THDATA", "structTHDATA.html", "structTHDATA" ],
    [ "TIMESPECFIXED", "structTIMESPECFIXED.html", "structTIMESPECFIXED" ],
    [ "VARIABLE", "structVARIABLE.html", "structVARIABLE" ],
    [ "yy_buffer_state", "structyy__buffer__state.html", "structyy__buffer__state" ],
    [ "yy_trans_info", "structyy__trans__info.html", "structyy__trans__info" ],
    [ "yyalloc", "unionyyalloc.html", "unionyyalloc" ],
    [ "YYSTYPE", "unionYYSTYPE.html", "unionYYSTYPE" ],
    [ "ZERNIKE", "structZERNIKE.html", "structZERNIKE" ]
];