#! /bin/bash


loopnb=$(cat LOOPNUMBER)

pname="aol${loopnb}_TTmult"


Cfits -n $pname << EOF
csetpmove system
readshmim aol${loopnb}_mfiltmult
setpix aol${loopnb}_mfiltmult $1 0 0
setpix aol${loopnb}_mfiltmult $1 1 0
exit
EOF
