#!/bin/bash

loopnb=$( head -1 LOOPNUMBER)

mkdir -p wfsdark

datestr=`date -u +%Y-%m-%d_%H:%M:%S`

cacao -n takedark << EOF
readshmim ircam2_dark
savefits ircam2_dark "!./wfsdark/wfsdark_${datestr}.fits"
exitCLI
EOF

echo "wfsdark/wfsdark_${datestr}.fits" > conf/conf_wfsdark_name.txt
