#!/bin/bash

NBARGS=2
pname=`echo "$0" | sed "s/\.\///g"`


function printHELP {
echo "------------------------------------------------------------------------"
echo "$(tput bold) $pname : Apply analog output voltate $(tput sgr0)"
echo "------------------------------------------------------------------------"
echo "  Apply analog output voltate"
echo "   "
echo " $(tput bold)USAGE:$(tput sgr0)"
echo "     $0 [-h] <channel> <voltage>"
echo ""
echo " $(tput bold)OPTIONS:$(tput sgr0)"
echo "     $(tput bold)-h$(tput sgr0)          help"
echo ""
echo " $(tput bold)INPUT:$(tput sgr0)"
echo "     <channel>                  output channel"
echo "                   A: PyWFS Camera X"
echo "                   B: PyWFS Camera Y"
echo "                   C: PyWFS pointing Tip"
echo "                   D: PyWFS pointing Tilt"
echo "     <voltage>                  voltage value [V]"
echo ""
echo " $(tput bold)NOTES:$(tput sgr0)"
echo "   output value written as ./status/stat_AnalogVoltage_<channel>.txt"
echo ""
echo "------------------------------------------------------------------------"
}


printHELP1 ()
{
    printf "%20s       Apply analog output voltate\n" "$0" 
}




# Transform long options to short ones
singlelinehelp=0
for arg in "$@"; do
  shift
  case "$arg" in
    "--help") set -- "$@" "-h" ;;
    "--help1") 
set -- "$@" "-h" 
singlelinehelp=1;
;;
    *)        set -- "$@" "$arg"
  esac
done


while getopts :h FLAG; do
  case $FLAG in
    h)  #show help
      if [ "$singlelinehelp" -eq "0" ]; then
      printHELP
      else
      printHELP1
      fi
      exit
      ;;
    \?) #unrecognized option - show help
      echo -e \\n"Option -${BOLD}$OPTARG${NORM} not allowed."
      printHELP
      ;;
  esac
done

shift $((OPTIND-1)) 







if [ "$1" = "help" ] || [ "$#" -ne $NBARGS ]; then
if [ "$#" -ne $NBARGS ]; then
    echo "$(tput setaf 1)$(tput bold) Illegal number of parameters ($NBARGS params required, $# entered) $(tput sgr0)"
fi
printHELP
        exit
fi



echo "ssh scexao@scexao2 '/home/scexao/bin/devices/analog_output.py voltage $1 $2'"
ssh scexao@scexao2 "/home/scexao/bin/devices/analog_output.py voltage $1 $2"

echo "$2" > ./status/stat_AnalogVoltage_$1.txt
